### ISSUE TITLE
Raining through blocks.

### ISSUE THREAD

**Issue by 5thRing** [Amulet-Team/Amulet-Map-Editor#118] opened 2020-10-02 22:43 UTC
It rains through blocks that have been edited with Amulet

It SEEMS to be only blocks that have replaced air.

If I use Amulet to replace a block that has been placed in Minecraft, then the rain does not go through.

If, for instance, I copy a structure that was built in Minecraft, and then paste in to to empty air, then when I play in Minecraft, rain passes through all of it.

**Expected behavior**
I expect blocks to not allow rain to fall through them.

**Desktop:**
 - OS: Windows
 - Version v0.7.1.1 (and a previous version confirmed)

sidenote: I would like to be able to mirror flip selections (not just rotate).

**Comment by gentlegiantJGC** [comment] 2020-10-03 06:44
Duplicate of #60

**Closed by gentlegiantJGC** 2020-10-03 06:45 UTC
