### ISSUE TITLE
[Bug Report] Wayland rendering problems

### ISSUE THREAD

**Issue by viridivn** [Amulet-Team/Amulet-Map-Editor#975] opened 2023-09-19 17:11 UTC
### Current Behaviour:
When running under wayland, much of the main UI renders strangely and is only visible when overlapping with certain graphics elements in the viewport.

### Expected behavior:

UI elements are always visible when they should be

### Steps To Reproduce:

Launch program under wayland (I used Hyprland, on arch linux), make sure the program does not run under xwayland.
Load a world and observe the visibility of UI controls in the world viewport

### Environment:

- OS: Linux
- Minecraft Platform: Java 
- Minecraft Version: 1.20.1
- Amulet Version: 0.10.19

### Additional context
The problem does not occur under Xwayland, confirming it is something to do with wayland
### Screenshots

https://github.com/Amulet-Team/Amulet-Map-Editor/assets/42524580/4d7d85a8-8d03-4da3-9aa6-f3b962f82956

**Comment by gentlegiantJGC** [comment] 2023-09-20 08:01
Duplicate of #127

**Closed as completed by gentlegiantJGC** 2023-09-20 08:01 UTC
Labels: type: bug, state: triage
