### ISSUE TITLE
GLXBadContext Error

### ISSUE THREAD

**Issue by arduinka55055** [Amulet-Team/Amulet-Map-Editor#126] opened 2020-11-07 12:28 UTC
**To Reproduce**
Run it on linux(from source) and choose 3D editor tab
(wine also has this problem)

**Screenshots**
(main.py:42349): Gdk-ERROR **: 14:21:52.171: The program 'main.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.

**Desktop (please complete the following information):**
 - OS: Linux (manjaro)
 - Versions Manjaro 20.2 Nibia, Python 3.8.6, x86_64 Linux 5.8 kernel 

**Additional context**
3D editor doesnt even render something, so error is inside of init of some 3D context

**Comment by gentlegiantJGC** [comment] 2020-11-07 12:33
Looks like a duplicate of #84. They may have found a solution earlier today. Can you try and see if that resolves the issue

**Comment by gentlegiantJGC** [comment] 2020-11-07 12:34
Here is a link for the fix. https://github.com/Amulet-Team/Amulet-Map-Editor/issues/84#issuecomment-723154691

**Comment by gentlegiantJGC** [comment] 2020-11-10 15:32
I am going to close this as a duplicate of #84. The next build should fix this. If it doesn't let us know.

**Closed by gentlegiantJGC** 2020-11-10 15:32 UTC
Labels: OS/Linux, bug, opengl

**Comment by arduinka55055** [comment] 2020-11-12 18:24
Thanks! it helped
