### ISSUE TITLE
Copy paste with rotate causes orientation error for torches, signs, ladders, stairs etc

### ISSUE THREAD

**Issue by Nesh-stack** [Amulet-Team/Amulet-Map-Editor#324] opened 2021-06-13 01:55 UTC
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

Copy-Paste & Rotate items.

Copy Paste much improved since last version but rotate is still not working properly.

Paste + Rotate leads to stairs in wrong orientation, torches, signs, ladders also do not sit properly

**To Reproduce**
1. Copy area
2. Go to target world
3. initial Placement
4. Rotate 90degrees (swivel orientation to face a different direction)

torches, signs, ladders to be attached to walls etc

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [e.g. 0.8.8
![bug2](https://user-images.githubusercontent.com/71952690/121792945-1490ba80-cc3e-11eb-968a-2e23f21d13f0.png)

![bug1](https://user-images.githubusercontent.com/71952690/121792934-02af1780-cc3e-11eb-8b42-65318e2ea2ad.png)

**Additional context**

**Comment by chrisjmartini** [comment] 2021-06-13 02:47
I am having the same issue. I exported structures from one bedrock world to another. I edited y rotation of the structures and then confirmed their positions, saved the changes. Loaded the world in Minecraft only to discover stairs, chests, doors, signs are at the wrong orientation (y coordinates didn’t change with selection when structure was rotated).

**Comment by TheCrazyInsanity** [comment] 2021-06-13 15:55
I have also had issues with this.

**Comment by gentlegiantJGC** [comment] 2021-06-13 16:16
This is a duplicate of #74 
Please use the search feature before reporting new issues.

**Closed by gentlegiantJGC** 2021-06-13 16:16 UTC
