### ISSUE TITLE
Schematic/structure pasting from files

### ISSUE THREAD

**Issue by XCharmyX** [Amulet-Team/Amulet-Map-Editor#107] opened 2020-09-16 09:55 UTC
Theres a bug where if you paste in a .structure or .schematic file, it will not place the stairs, torches, fences, banners, trapdoors or anything that has directional properties, correctly.

You'd expect it to just paste in the structure without having any block placement issues.

So far, this issues has only been tested on windows 10, java edition.

**Comment by gentlegiantJGC** [comment] 2020-09-20 15:30
Are you applying a rotation to it when you are trying to paste it? If so this is a duplicate of #74

**Comment by XCharmyX** [comment] 2020-09-20 15:35
It happens either way.

**Comment by gentlegiantJGC** [comment] 2020-09-20 15:39
Without a rotation it should paste the blocks with the same rotations that they had in the copied version

**Comment by gentlegiantJGC** [comment] 2020-09-20 15:40
Can you upload some photos to show what you mean. I have a feeling this is a duplicate of #74

**Comment by XCharmyX** [comment] 2020-09-20 19:58
Heres some pictures of what happens. Doesnt matter if you rotate it or not

![weird](https://user-images.githubusercontent.com/60596287/93720860-40d64980-fb8c-11ea-8569-38bda61244c6.PNG)
![doors](https://user-images.githubusercontent.com/60596287/93720863-4338a380-fb8c-11ea-9184-4e717afefcc8.PNG)
![fences](https://user-images.githubusercontent.com/60596287/93720865-43d13a00-fb8c-11ea-9878-ce24ae050fe4.PNG)
![stairs](https://user-images.githubusercontent.com/60596287/93720866-45026700-fb8c-11ea-9491-09aa3e86808a.PNG)

**Comment by gentlegiantJGC** [comment] 2020-09-20 20:03
ah right okay. This is a duplicate of #110 although technically you created the bug first but I didn't realise what the problem was until after.
It should be fixed in the build we just released.

**Closed by gentlegiantJGC** 2020-09-20 20:03 UTC
Labels: more information needed
