### ISSUE TITLE
[Bug Report] When the bedrock save file is cloned to java, some block metadata cannot be cloned together

### ISSUE THREAD

**Issue by RemyYYZ** [Amulet-Team/Amulet-Map-Editor#938] opened 2023-07-12 13:02 UTC
## Bug Report
No.1 Wall cannot connect
No.2 Sign text is missing (The bug seems that someone has reported it before, but it seems that it has not been resolved.)

### Current Behaviour:
No.1 Wall cannot connect
Original bedrock save file：
![bedrock wall](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/105116818/14feb9d8-15dd-411f-903c-21f8568473ae)
After cloning to java：
![java wall](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/105116818/4271df83-4eef-444a-bcd9-9981d07bb6f8)
No.2 Sign text is missing
After cloning to java：
![java sign](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/105116818/62a067e3-c6aa-4c9e-8804-30799c90c5c2)

### Expected behavior:
No.1 The walls should be connected together，like this:
![Expected behavior](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/105116818/14feb9d8-15dd-411f-903c-21f8568473ae)
No.2 The sign text is cloned along with the save file

### Environment:
- OS: Windows
- Minecraft Platform: Java and Bedrock
- Minecraft Version: Bedrock 1.19.83 /Java 1.19.4
- Amulet Version: 0.10.15

**Comment by gentlegiantJGC** [comment] 2023-07-15 12:32
I can't remember if we compute the connection state. In Bedrock that is computed at runtime.
#939 will track the sign issue.

**Comment by gentlegiantJGC** [comment] 2023-07-15 14:42
The walls issue is a duplicate of #726

**Closed as completed by gentlegiantJGC** 2023-07-15 14:42 UTC
Labels: type: bug, state: triage
