### ISSUE TITLE
Lighting Error in edited chunk

### ISSUE THREAD

**Issue by Pacomatic1** [Amulet-Team/Amulet-Map-Editor#300] opened 2021-05-24 19:26 UTC
OS: Windows 10
Version: 0.8.4 (64-bit)
World Type: Java 1.16.5, Vanilla (Singleplayer and not Bukkit or smth)
I was editing my creative world to remove something, and while it removed fine, loading up the world was hilarious.

The chunk in which the command block was located had a lighting error-- Everything in the chunk was dark and a gazillion mobs had spawned. Wasn't much, I could just do a few block-updates, but still.

How to get:
1. Go into MC and make a new world.
2. Open it in Amulet
3. Do literally anything to a chunk (what i did was delete one block)
4. Open in MC

And now, lighting error!

**Comment by Pacomatic1** [comment] 2021-05-24 19:26
300th bug
cool

**Comment by gentlegiantJGC** [comment] 2021-05-25 11:32
This is a duplicate of #44

**Closed by gentlegiantJGC** 2021-05-25 11:32 UTC
