### ISSUE TITLE
The progress bar UI is not displaying a correct estimated time & console error.

### ISSUE THREAD

**Issue by StealthyExpertX** [Amulet-Team/Amulet-Map-Editor#227] opened 2021-03-23 21:53 UTC
The progress bar shows an incorrect estimated remaining time of 0:00:00 during the pruning of the chunks while using chunk view this lasted serval minutes.

**Steps to reproduce the behavior:**
**1.** Open a Java 1.16.5 world in the 3D editor/viewer.
**2.** Go into chunk view and select a large area of at least 50x50 chunks or greater.
**3.** Run the prune chunks operation or any other large selection operation and watch the progress dialog popup show.
**4.** Notice the estimated time is incorrect or frozen during the operation and says not responding.

**The expected behavior:**
Should show a semi-accurate estimation of time for completion in the progress bar UI.

**Screenshot:**
![image](https://user-images.githubusercontent.com/17806994/112221176-850adb00-8bfd-11eb-954f-5cdd2709056d.png)

**OS Information:**
 - OS: Windows
 - Device: Desktop
 - Version V0.8.1
 - I have a triple monitor setup if that means anything?
 
 **NOTE:** that this error was constantly showing in the console in a loop multiple times.
 ```py
 Traceback (most recent call last):
  File "amulet_map_editor\programs\edit\api\behaviour\pointer_behaviour.py", line 83, in _pre_draw
  File "amulet_map_editor\programs\edit\api\behaviour\chunk_selection_behaviour.py", line 128, in _update_pointer
  File "amulet_map_editor\programs\edit\api\behaviour\raycast_behaviour.py", line 102, in get_2d_mouse_location
ZeroDivisionError: float division by zero
 ```

**Comment by gentlegiantJGC** [comment] 2021-03-23 22:09
Yeh those are two separate issues. The first is a duplicate of #204 
The loading bar is correct and the actual operation runs pretty quickly but in creating the undo point it is loading all the chunks. I know this is not ideal but it is the way it is currently done. That bug report is to update the loading bar while that is done. Normal operations do not take that long so it hasn't been an issue yet.
Can you open a new issue for the second issue.

**Closed by gentlegiantJGC** 2021-03-23 22:09 UTC

**Comment by StealthyExpertX** [comment] 2021-03-23 23:51
Alright, will do 👍
