### ISSUE TITLE
[Bug Report] Cant load my worlds

### ISSUE THREAD

**Issue by MetalMadnesss** [Amulet-Team/Amulet-Map-Editor#917] opened 2023-06-12 12:51 UTC
### Current Behaviour:

Not able to open world
### Expected behavior:

Be able to open world
### Steps To Reproduce: 

try to open world
### Environment:

- OS: Windows 
- Minecraft Platform:  Bedrock 
- Minecraft Version: 1.20.0
- Amulet Version: V0.10.11

### Additional context
here is the error i get:

'DimensionName'
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\amulet_ui.py", line 183, in open_level
  File "amulet_map_editor\api\framework\pages\world_page.py", line 71, in __init__
  File "amulet\level\load.py", line 32, in load_level
  File "amulet\api\level\world.py", line 14, in __init__
  File "amulet\api\level\base_level\base_level.py", line 63, in __init__
  File "amulet\api\wrapper\format_wrapper.py", line 337, in open
  File "amulet\level\formats\leveldb_world\format.py", line 456, in _open
  File "amulet\level\formats\leveldb_world\format.py", line 395, in _reload_world
  File "amulet_nbt\\_compound.pyx", line 405, in amulet_nbt._compound.CyCompoundTag.get_string
  File "amulet_nbt\\_compound.pyx", line 416, in amulet_nbt._compound.CyCompoundTag.get_string
KeyError: 'DimensionName'

i am able to load them on V0.10.10 but this V0.10.11 version gives me a error.
### Screenshots

![bandicam 2023-06-12 14-45-03-372](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/136338875/6eb856e5-72a8-482b-a408-d9c6d7ee028d)

### Worlds
i tried uploading the world here but it says file is not supported.

**Comment by gentlegiantJGC** [comment] 2023-06-13 10:35
Duplicate of #910

**Closed as completed by gentlegiantJGC** 2023-06-13 10:35 UTC
Labels: type: bug, state: triage

**Comment by MetalMadnesss** [comment] 2023-06-13 10:41
ok so how do i fix it?
