### ISSUE TITLE
Polished Andesite/Blackstone stairs do not rotate properly

### ISSUE THREAD

**Issue by qmagnet** [Amulet-Team/Amulet-Map-Editor#329] opened 2021-06-17 17:14 UTC
**Describe the bug**
When using the copy paste structure from java to bedrock, polished shed andesite stairs and polished blackstone stairs did not rotate their direction

**To Reproduce**
1. Place stairs
2. Run amulet and rotate structure
3. Save and see in world

**Expected behavior**
Stairs should rotate properly as other blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/13902631/122443678-d103bc80-cf6d-11eb-8fcc-9ad91f0f475b.png)

**Desktop (please complete the following information):**
 - 1.17.0 Bedrock Win 10

**Additional context**
Only tested with those two types. Other stairs may be affected.

**Comment by gentlegiantJGC** [comment] 2021-06-17 18:12
This is a duplicate of #74

**Closed by gentlegiantJGC** 2021-06-17 18:12 UTC
