### ISSUE TITLE
Mobs / inventory aren’t converted

### ISSUE THREAD

**Issue by Itzikr1** [Amulet-Team/Amulet-Map-Editor#871] opened 2023-01-30 16:35 UTC
Hi
Tried to covert a world, created from the education edition and the conversion worked, apart from the inventory (not a big issue) and the mobs that were created (a big issue)

Any idea how to help here? I have the source files from the education edition world..

**Comment by gentlegiantJGC** [comment] 2023-01-31 12:09
Duplicate of #171 and #155

**Closed as completed by gentlegiantJGC** 2023-01-31 12:09 UTC
