### ISSUE TITLE
Void below y=0 on Java 1.17/1.18 conversion to Bedrock

### ISSUE THREAD

**Issue by mikezimm** [Amulet-Team/Amulet-Map-Editor#490] opened 2021-12-08 00:46 UTC
Similar issue as #473, different scenario for me:

I converted a Java world and in both chunks that were last loaded in 1.17 as well as chunks loaded and blended in 1.18 Java, there is void under y=0

One other issue I found during this test... there is a ring of "void" around the areas loaded in Java 1.18.
The void ring looks to be about 7 chunks.

![image](https://user-images.githubusercontent.com/49648086/144767994-465b5199-7df8-4976-8f73-fb5294b9cf6e.png)

Creating new issue per gentalgianJGC's reply: 
_Originally posted by @mikezimm in https://github.com/Amulet-Team/Amulet-Map-Editor/issues/473#issuecomment-986320440_

**Comment by mikezimm** [comment] 2021-12-08 01:58
Steps to reproduce:
Used MCA Selector to prune 1.17.1 chunks.
Copied selected region files to brand new 1.17.1 Java world (**730608626-1_17_1 Amu8_16a4**)
- r.1.35 - Modern Mansion base
- r.2.35 - Modern Mansion base
- r.-5.-3 - Desert Jungle Oasis
- r.-7,-4 - Jungle Mesa Mineshaft

Created copy of world here:  **730608626-1_17_1 1_18 Blend Amu8_16a4**
Opened 730608626-1_17_1 Amu8_16a4 in Java 1.18 to get best blending - Render Distance 4 chunks
/tp @s   -2432 135 -1423 (  r.-5.-3 - Desert Jungle Oasis )
Dug to -10 and confirmed -Y was generated
/tp @s -3385 135 -1547 ( r.-7,-4 - Jungle Mesa Mineshaft )
/tp @s 890 135 18155 ( r.1.35 - Modern Mansion base )
Moved around mansion base to have it blend more
    to 887, 83, 18061;  
    then to 1007, 86, 18034;
    then to 968, 90, 18195,
    then to 882, 90, 18200,
    then back to my starting point
    Then quit the game

Created new Bedrock 1.18 world:  730608626-J1.18 Blend 8.16a4 (Render dist 53 chunks)
Converted from:  JAVA 1.18:  730608626-1_17_1 1_18 Blend Amu8_16a4
Converted to:  Bedrock 1.18:  730608626-J1.18 Blend 8.16a4
Created Copy of... Bedrock
Opened Bedrock world:  730608626-J1.18 Blend 8.16a4
Teleported to same locations and took some screenshots in replies.

Memo to self:
Used files from
..\Desktop\Mashup\730608626 Tested and Approved Regions to import\1.0 ALL REGION FILES - Expand Mansion

Brand new 1.17.1 Java World:  730608626-1_17_1 Amu8_16a4

## Mansion base regions in MCA Selector after loading in 1.18
![image](https://user-images.githubusercontent.com/49648086/145133299-c614f2ed-3a42-4cbf-a3a6-b758cf875fa6.png)

## Jungle regions in MCA Selector after loading in 1.18
![image](https://user-images.githubusercontent.com/49648086/145133351-25c84620-57a8-4dfd-8834-888c52601ea5.png)

**Comment by mikezimm** [comment] 2021-12-08 02:02
In Bedrock under r.-7,-4
![image](https://user-images.githubusercontent.com/49648086/145135277-9c5d654e-e8fb-4360-bf49-a0eda59b7669.png)

**Comment by mikezimm** [comment] 2021-12-08 02:21
## This is 
r.1.35 - Modern Mansion base
r.2.35 - Modern Mansion base

Area marked in Red were the original areas loaded and blended in 1.18 Java
Purple marked "Gap" all around is similar to Mesa-Jungle image above... 
Yellow is an area that was filled in -Y inside the void gap.

Looks like there is about a 112 block or 7 chunk void ring around all the areas I copied over.
![image](https://user-images.githubusercontent.com/49648086/145136140-3b6dcde1-8eb8-478a-9c3d-1403f4b0772f.png)

## Coordinates of gap corner on left ( inside )
![image](https://user-images.githubusercontent.com/49648086/145136646-8a5f0d1b-b9d1-4f97-9c68-7fd65765a89c.png)

## Coordinates of gap on the outside left
![image](https://user-images.githubusercontent.com/49648086/145136791-89775550-0d3c-4dc6-aeeb-0c8de11a477b.png)

**Comment by gentlegiantJGC** [comment] 2021-12-09 13:44
Can you see if this is still an issue in 0.8.17a1

**Comment by mikezimm** [comment] 2021-12-10 21:54
@gentlegiantJGC ,

I tested the issue:
1. Created new Java 1.17.1 world:  730608626-1_17_1 v0.8.17a1
2. Replaced all region files with those from:
3. ..\Desktop\Mashup\730608626 Tested and Approved Regions to import\1.0 ALL REGION FILES - Expand Mansion
4. Created and loaded new Bedrock world:  730608626-1_17_1 v0_8_17a1
5. Copied Java world to Bedrock.

Got these errors:
2021-12-10 16:26:26,705 - pymctranslate - INFO - PyMCTranslate Version 160
2021-12-10 16:27:26,539 - pymctranslate - WARNING - Could not find registered value for biome 17. Reverting to plains
2021-12-10 16:27:31,861 - pymctranslate - WARNING - Could not find registered value for biome 164. Reverting to plains
2021-12-10 16:27:57,723 - pymctranslate - WARNING - Could not find registered value for biome 22. Reverting to plains
2021-12-10 16:28:02,913 - pymctranslate - WARNING - Could not find registered value for biome 162. Reverting to plains
2021-12-10 16:28:54,151 - pymctranslate - WARNING - Could not find registered value for biome 18. Reverting to plains

## Game Results:
Loaded world in Bedrock.
**Entire game crashed** when trying to load the upgraded world.

## Other notable results....
To take out my Java world edits from the test about the game crash,
I just did another test:
Created Java 1.17.1 world with 2 chunk render distance.
Did NOT modify it and Did NOT load in Java 1.18
Used v0.8.17a to convert to Bedrock.
**Opened the converted world in bedrock and it crashed**.
And this was with minimal chunks on newly created Java 1.17.1 world.


These were the only errors in the log:
2021-12-10 16:38:43,658 - pymctranslate - INFO - PyMCTranslate Version 160
2021-12-10 16:40:10,659 - pymctranslate - WARNING - Could not find registered value for biome 28. Reverting to plains
2021-12-10 16:40:12,101 - pymctranslate - WARNING - Could not find registered value for biome 18. Reverting to plains

If you have some instructions, I can upload world files if it helps.

Thanks!

**Comment by gentlegiantJGC** [comment] 2021-12-10 22:29
Copied from the other report:
I haven't checked all the numbers but all of the biome IDs you sent that I have looked up are invalid biomes.
https://minecraft.fandom.com/wiki/Biome/ID
You said you copied region files from another world. Is this a vanilla world. I am trying to work out why invalid biome IDs would be written to the world.

**Comment by mikezimm** [comment] 2021-12-11 02:20
@gentlegiantJGC , the world was vanilla Java 1.17.1.

The only thing I did with the first one (with the 6 errors was use MCA Selector to prune the chunks and relocate them.

The second test I did with the 2 biomes were from creating a Java 1.17.1 world from scratch today.

If there is a place I can upload the world I will be happy to.

**Comment by gentlegiantJGC** [comment] 2021-12-11 14:03
In the future can you open multiple tickets. You have listed a number of different issues and it becomes difficult to keep track.
Issue 1) The crashing. I think this is linked to #475 which I have just solved. Hopefully the next alpha will resolve that issue.
Issue 2) There is void below the centre region. This may be due to a bug in Amulet which may have been fixed in a prior release.
Issue 3) There is void around the area. Not sure what would be causing this.
Issue 4) Invalid biomes in your world. Unless there is a reason why these biomes exist in your world I would say that Amulet is working as intended by reverting them to plains since it doesn't know how to handle them.

**Comment by mikezimm** [comment] 2021-12-13 21:13
@gentlegiantJGC , 

Does this commit (  https://github.com/Amulet-Team/Amulet-Core/commit/2ffcb23cc59033a48366ce4eef366050ca2dcdaa ) resolve the two unkown biomes (18 and 28)?

Also, I'll create a separate issue for my issue 3) above... about the void surrounding chunks.

If you can let me know how to upload game files I can upload both the before (Java) and after (Bedrock) worlds.

**Comment by gentlegiantJGC** [comment] 2021-12-13 21:18
You said the biome issue was with a Java world right? Those values aren't valid biome IDs for a vanilla Java world.
You should just be able to upload the zip of the world to a message here

**Comment by gentlegiantJGC** [comment] 2021-12-13 21:19
That commit should fix the crashing issue on bedrock

**Comment by mikezimm** [comment] 2021-12-15 22:10
@gentlegiantJGC 

Did some follow-up testing on v0.8.17a2:

1. Created vanilla Java 1.17.1 world (seed:  730608626)
2. Opened in Java 1.17.1 at 8 chunks render distance
3. Saved and closed.
4. Created new Bedrock 1.18.2 vanilla world (seed:  730608626)
5. Opened Amulet v0.8.17a2
6. Converted per screenshot

## Got same biome errors shown below BUT this time game didn't crash:
To confirm, this was vanilla 1.17.1 world I just created, no mods just straight vanilla Java.

## I did notice 3 things this time:
- Game didn't crash!  :)
- Bedrock did generate negative z blocks  :)
- There were some strange blending issues (see screenshot).

```
2021-12-15 16:47:44,165 - pymctranslate - INFO - PyMCTranslate Version 160
2021-12-15 16:51:19,001 - pymctranslate - WARNING - Could not find registered value for biome 28. Reverting to plains
2021-12-15 16:51:20,433 - pymctranslate - WARNING - Could not find registered value for biome 18. Reverting to plains
```
I am attaching my Java world here
[730608626-Van1_17_1 12-15.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7722931/730608626-Van1_17_1.12-15.zip)

Bedrock world here (I think this was before I came in and got the screenshot below of the world)
[xWC6YQgwAAA=.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7722938/xWC6YQgwAAA.zip)

Here's the screenshot of amulet to confirm folders and game saves
![image](https://user-images.githubusercontent.com/49648086/146271081-6f29e8d7-966f-4133-a363-58f99c4972ce.png)

## Here's a screenshot of what it looks like when I opened Bedrock:

![image](https://user-images.githubusercontent.com/49648086/146272067-545ae912-0a8b-494d-b4b3-3cdad7c5201a.png)

**Comment by mikezimm** [comment] 2021-12-15 22:12
@gentlegiantJGC , one question on the upgrade process...

Am I supposed to load all regions in Java 1.18 before converting to Bedrock?  Or should it not matter?
I'm asking because of the lack of blending in the screenshot above.

It would be a challenge to load all the relevant chunks in Java 1.18 before converting so I'm just asking if I'm doing something wrong.

Thanks!

**Comment by gentlegiantJGC** [comment] 2021-12-15 22:19
Bedrock only blends chunks when loading from the old chunk format. Amulet writes the chunks in the newest chunk format for that world so blending does not happen.
I think if you open it in Java it will do the blending when you go near and then convert.

**Comment by mikezimm** [comment] 2021-12-16 21:29
@gentlegiantJGC , I see.
"so blending does not happen" made me think about my previous testing.
I moved back over to the area in the screenshot that was 1.17.1 generation (where blending didn't happen).

And then dug to -0 and it turns out there is still void under it.

So long term, what do you think your goal will be with Amulet?
Will we need to load all java world chunks in 1.18 Java before converting?
Then maybe import to bedrock using Amulet.
Then go back and delete border chunks and have the game regenerate the chunks?
Maybe then the #476 suggestion could help to smooth out the borders?

Just curious what the goals might be.

Thanks

![image](https://user-images.githubusercontent.com/49648086/146450795-3c6fa65e-34b9-4d99-85a1-45a34ac422bd.png)

**Comment by gentlegiantJGC** [comment] 2022-01-12 17:21
Amulet saves out chunks in the newest format that is compatible with the world version. Changing that would mean changing quite a bit.
The conversion process in Amulet just copies all the existing data from one world to another. It isn't aware of the other various limitations of the format.
Perhaps we could add an option somehow to specify an older version to save data as but that would also mean that newer blocks would get stripped out.

**Comment by gentlegiantJGC** [comment] 2022-01-12 17:24
I am going to close this bug report because it is quite long and does not concentrate on a single issue.
If the issues still exist can you open a new bug report for each of them.

**Closed by gentlegiantJGC** 2022-01-12 17:24 UTC

**Comment by mirijambar-tech** [comment] 2026-01-03 20:44
Minecraft
