### ISSUE TITLE
Does not copy and paste paintings, item frames, and armour stands.

### ISSUE THREAD

**Issue by ric4397** [Amulet-Team/Amulet-Map-Editor#799] opened 2022-09-22 19:33 UTC
I copied a building that I built and furnished using creative mode, and pasted it into my survival world, but my paintings, item frames and armor stands were not there in when I opened up my survival world.

**Comment by gentlegiantJGC** [comment] 2022-09-23 09:07
Duplicate of #171

**Closed as completed by gentlegiantJGC** 2022-09-23 09:07 UTC
Labels: type: bug, state: triage
