### ISSUE TITLE
Error loading Java resource pack

### ISSUE THREAD

**Issue by Hema-Chandra06** [Amulet-Team/Amulet-Map-Editor#553] opened 2022-01-27 11:53 UTC
![sdiojdlmp;oeifjlm](https://user-images.githubusercontent.com/96871624/151353834-d721a3f1-8b77-4235-a463-df3705ce8897.JPG)

**Comment by gentlegiantJGC** [comment] 2022-01-27 12:58
are you able to access this url?
https://launchermeta.mojang.com/mc/game/version_manifest.json

**Comment by Hema-Chandra06** [comment] 2022-01-28 09:54
> are you able to access this url? https://launchermeta.mojang.com/mc/game/version_manifest.json

yes

**Comment by gentlegiantJGC** [comment] 2022-02-13 10:53
I should look into adding retry support for this and a manual fallback for the user to specify a jar file.

**Comment by gentlegiantJGC** [comment] 2022-04-26 10:57
I am going to close this as a duplicate of #419 
While not the exact same error the result is the same

**Closed by gentlegiantJGC** 2022-04-26 10:57 UTC
Labels: type: bug, priority: medium
