### ISSUE TITLE
[Bug Report]The fence cannot be connected automatically

### ISSUE THREAD

**Issue by RSCENTCOM** [Amulet-Team/Amulet-Map-Editor#960] opened 2023-09-02 06:28 UTC
### Current Behaviour:
When the bedrock edition world is converted to the java edition world, the connected fence is not automatically connected

### Expected behavior:
When the world transitions, the connected fence remains connected

### Steps To Reproduce:
1. Put a row of fences in the Bedrock world,
2. Use Amulet to convert to the Java world
3. After opening the Java world, you will see that the fence is not automatically connected

### Environment:
- OS: Windows
- Minecraft Platform:  Bedrock |  Java
- Minecraft Version: 1.20.15.1.0 |  1.20
- Amulet Version: <!-- Write the version number of Amulet here. 0.10.19

Additional context
Since Minecraft was updated to v1.18, Amulets larger than v0.10.13 do not seem to be able to automatically attach fences

### Screenshots
Bedrock:
![Bedrock](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/103917088/3cf2b6a1-5a3b-46b9-b029-31db4676e869)
Java（Converted）:
![Java](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/103917088/7db032c3-131d-4350-b400-7ad0a38c3c59)

### Worlds
[MC_Bedrock.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12503304/MC_Bedrock.zip)
[MC_Java.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/12503305/MC_Java.zip)

**Comment by gentlegiantJGC** [comment] 2023-09-02 08:07
Duplicate of #726

**Closed as completed by gentlegiantJGC** 2023-09-02 08:07 UTC
Labels: type: bug, state: triage
