### ISSUE TITLE
[Bug Report] Some of the Sealanterns and Concrete Powder Are NOT Converted

### ISSUE THREAD

**Issue by AnnoyingVillager** [Amulet-Team/Amulet-Map-Editor#788] opened 2022-09-12 16:46 UTC
## Bug Report
Some of the Sealanterns and Concrete Powder Are NOT Being Converted.

### Current Behaviour:
When converting worlds from bedrock edition to java edition, some of the sealanterns and concrete powder are not being converted.

### Expected behavior:
All the sealanterns and concrete powder should be converted.

### Steps To Reproduce:

1. Choose a bedrock world which contains many sealanterns / concrete powder
2. Convert it into a java world
3. Open the java world and some of the sealanterns / concrete powder disappear.
4. Check the console log you can see warning info for sealanterns / concrete powder.

### Environment:
- OS: Windows 11
- Minecraft Platform: Bedrock to Java
- Minecraft Version: BE1.19.22 to JE1.19
- Amulet Version: 0.10.2, 0.10.1, 0.10.0, 0.9.*

### Screenshots
![image](https://user-images.githubusercontent.com/94441745/189706520-388c0776-6ec3-40b5-8e56-45e304e1c5a3.png)
![image](https://user-images.githubusercontent.com/94441745/189710268-51f99c71-46c8-41c1-89cb-1adfc554c7be.png)

### Worlds

[Java World](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9549976/City2.zip)
[Bedrock World](https://github.com/Amulet-Team/Amulet-Map-Editor/files/9609866/City2BE.zip)

**Comment by AnnoyingVillager** [comment] 2022-09-20 17:14
It seems that this issue only happens after the world was updated from 1.18.12(bedrock) to a higher version as sea lanterns placed recently has no such issue.

**Comment by gentlegiantJGC** [comment] 2022-09-21 08:00
I am aware of this issue and know what is causing it.
I am working on a project to extract data from Bedrock edition so that issues like this should not happen again.

**Comment by gentlegiantJGC** [comment] 2022-10-04 09:47
This is fixed in the translator and will be included in the next build.

**Comment by AnnoyingVillager** [comment] 2022-10-04 17:55
> This is fixed in the translator and will be included in the next build.

I've tried the new build, but there are still sealanterns missing. 😢
![image](https://user-images.githubusercontent.com/94441745/193891093-31017558-8c6c-4158-a26b-8ad83fd4fee7.png)
![image](https://user-images.githubusercontent.com/94441745/193965676-30364fd4-e2dc-4bc4-b0f3-4e5fdf1c7513.png)

**Comment by gentlegiantJGC** [comment] 2022-10-04 18:03
Hmm okay. Is this after converting again?

**Comment by AnnoyingVillager** [comment] 2022-10-04 18:19
> Hmm okay. Is this after converting again?

Yes, but this time I converted to an 1.18.2 world instead of 1.19 world. The console log still produced a warning that it could not find a translation information.

**Comment by gentlegiantJGC** [comment] 2023-06-28 14:22
Is this still an issue in the newest version of Amulet?

**Comment by AnnoyingVillager** [comment] 2023-06-29 10:48
Yes, there're still sealanterns missing, and I still find warnings in the console log.
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/94441745/b5a198eb-e711-4724-b867-1d4d11cfc1af)
![2023-06-29_18 43 19](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/94441745/5f277df8-865a-412f-bce1-b82b115ce39b)

**Comment by AnnoyingVillager** [comment] 2023-06-29 11:15
This is the latest copy of the BE world. I hope this would help.
The missing sealanterns can be found near (-221,70,514) after being converted to JE world.
[Bedrock World](https://1drv.ms/u/s!Av9BRPd9HFw4jmZTPA-FaqjygXvw?e=wOsdcV)

**Comment by gentlegiantJGC** [comment] 2023-07-01 15:02
I see what the issue is. Will get this fixed.

**Comment by gentlegiantJGC** [comment] 2023-07-01 15:25
This should be fixed in the next build

**Closed as completed by gentlegiantJGC** 2023-07-01 15:25 UTC
Labels: type: bug, translator, priority: high
