### ISSUE TITLE
severe block placement bug if you do paste and rotate

### ISSUE THREAD

**Issue by Heliopolisking** [Amulet-Team/Amulet-Map-Editor#431] opened 2021-09-25 12:22 UTC
So when you use Amulet and you copy a volume and after you do paste , and maybe you whant to rotate this volume or do mirror there is an important bug that make to you lost a lot of time in the game to  fix the erros of this bug .
The software dont rotate in the correct orientacion blocks like stairs , fences , iron  fences , buttons , all types of  walls  and i think more types of blocks , here i have in game screenshots to show this important bug , i precise that i use Amulet from almost 1 week  im not an expert now of this applicacion maybe i can do something wrong , but to be honest i find this thing not good , i whrite it sure for the better development of the software . 

this is a window almost ok but if we look whats happen if i do rotate 
![2021-09-25_13 57 12](https://user-images.githubusercontent.com/91331773/134771194-093ac993-e6ec-4a5d-8f81-4b5d3da59cbe.png)
how is possible to see a lot of blocks are not orientated in correct posicion , walls are floating in the air , stairs block are not rotated and remain in original orientacion like before i do rotate 
![2021-09-25_13 57 25](https://user-images.githubusercontent.com/91331773/134771286-f54d5eba-6497-47bb-bfdd-6f9ee73c88dd.png)

in these pictures in possible to see better whats happen with this bug just look at the buttons and at the stairs blocks 
![2021-09-25_13 56 58](https://user-images.githubusercontent.com/91331773/134771313-dd4cf440-8ca6-43ce-9b21-aa5cef1d2ec3.png)
 how is possible to see the button and others blocks are rotated but dont change his original orientacion 
![2021-09-25_13 56 24](https://user-images.githubusercontent.com/91331773/134771377-c10db8ed-4a63-406e-b727-a52f8afcae59.png)

I hope a lot this bug will be fixed is possible to find it  in the 8.12 version and also in the new 8.13 version of Amulet

**Comment by gentlegiantJGC** [comment] 2021-09-25 12:31
Duplicate of #74. Please use the search feature

**Closed by gentlegiantJGC** 2021-09-25 12:31 UTC
