### ISSUE TITLE
[Feature Request] Search Function

### ISSUE THREAD

**Issue by prototype464** [Amulet-Team/Amulet-Map-Editor#587] opened 2022-03-04 06:33 UTC
### The Problem
Trying to search for certain things in a world file is not currently possible, as you can only view / edit worlds.

### Feature Description
Add a function that would allow you to search for blocks in a world (I.E. signs or chests)

### Alternatives
No known alternatives.

### Additional context
That's pretty much it!

**Comment by gentlegiantJGC** [comment] 2022-03-09 11:54
duplicate of #320

**Closed by gentlegiantJGC** 2022-03-09 11:54 UTC
Labels: enhancement
