### ISSUE TITLE
Not compatible with Bedrock 1.17.41.1 world

### ISSUE THREAD

**Issue by wtfbbqhax** [Amulet-Team/Amulet-Map-Editor#454] opened 2021-11-06 18:43 UTC
# Description

I'm a new user, and didn't see any prior reports or disclaimer in the amuletmc.com/readme for this expectation.

Amulet V0.8.15 is not loading my Bedrock world correctly (1.17.41.1), after loading it just shows checkerboard of the world. This happens with all worlds (overworld, the_nether, and the_end).

![Amulet-Bedrock-1 17 41](https://user-images.githubusercontent.com/7323455/140620324-c4becacb-5f31-4764-9489-02a72c7c842f.PNG)

Another interesting note about the coordinates (-3000000)

I have confirmed it works with my 1.17.34.2 bedrock world

**Comment by gentlegiantJGC** [comment] 2021-11-06 19:41
This is probably a duplicate of #452 
Do you have the experimental toggle enabled?

**Comment by wtfbbqhax** [comment] 2021-11-23 16:17
Yes, it was/is a experimental toggled world.

**Comment by gentlegiantJGC** [comment] 2021-12-09 17:23
The newest alpha should now support this.

**Closed by gentlegiantJGC** 2021-12-09 17:23 UTC
Labels: enhancement
