### ISSUE TITLE
[Bug Report] It hardly to look the screen.

### ISSUE THREAD

**Issue by xCryselunex** [Amulet-Team/Amulet-Map-Editor#1025] opened 2024-02-14 16:22 UTC
### Steps To Reproduce:

1. Open to Amulet Map Editor using terminal "python3 -m amulet-map-editor"
2. Open any world in java.
3. Click to 3D Editor
4. See error like screen.

Bugs: it looks the screen is not good.

### Environment:

- OS: Ubuntu 23.10 (Stock Python by Ubuntu - 3.11)
- Minecraft Java 1.20.4
- Minecraft Version: 1.20.4
- Amulet Version: Latest

Here in video:
[Gravação de ecrã a partir de 2024-02-14 16-03-06.webm](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/107869004/918fbeb1-f5b6-441b-9571-5270c34ff1d1)

**Comment by gentlegiantJGC** [comment] 2024-02-14 16:55
Duplicate of #127

**Closed as completed by gentlegiantJGC** 2024-02-14 16:55 UTC
Labels: type: bug, state: triage
