### ISSUE TITLE
error after world conversion How can i solve it

### ISSUE THREAD

**Issue by Hema-Chandra06** [Amulet-Team/Amulet-Map-Editor#534] opened 2022-01-13 12:51 UTC
![git](https://user-images.githubusercontent.com/96871624/149333470-ad3f3871-7cd6-41e2-a784-ced638faa3fb.JPG)

**Comment by gentlegiantJGC** [comment] 2022-01-13 13:27
This is a duplicate of #402 
Please search for your issue before opening a new issue.

**Closed by gentlegiantJGC** 2022-01-13 13:27 UTC
