### ISSUE TITLE
There are performance problems when processing with very big maps

### ISSUE THREAD

**Issue by yqs112358** [Amulet-Team/Amulet-Map-Editor#330] opened 2021-06-18 00:25 UTC
I have tried my server's map which was over 600MB, and it takes so long time to save when closing the map that I have to kill amulet in task manager. Hoping that performance can be improved in future versions.

**Comment by gentlegiantJGC** [comment] 2021-06-23 12:55
Could you elaborate. Is this the same issue as #321 ?

**Comment by yqs112358** [comment] 2021-06-23 13:54
yeah,, i think it look like the same
since python's perfomance is considered inferior to other languages in large scale data processing

**Comment by gentlegiantJGC** [comment] 2021-06-23 13:56
is the world you are editing a Java or Bedrock world?

**Comment by yqs112358** [comment] 2021-06-23 14:00
Of course. It take so much time that windows tells me it stops working when i finished editing a large map which is about 600MB, and saving the map into the save

**Comment by yqs112358** [comment] 2021-06-23 14:01
Its a bedrock world
But i think java ones will have similar performance problem when processing a very large map

**Comment by gentlegiantJGC** [comment] 2021-06-23 14:04
We run the compacting logic when you close the world to remove unused data from the world. That just takes a little while for larger worlds. That process is run by the leveldb dll which is compiled c++
I am going to close this as a duplicate of #321

**Closed by gentlegiantJGC** 2021-06-23 14:04 UTC
