### ISSUE TITLE
light is not copied if you paste 

### ISSUE THREAD

**Issue by Heliopolisking** [Amulet-Team/Amulet-Map-Editor#428] opened 2021-09-24 14:27 UTC
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**

**To Reproduce**
1. Go to amulet
2. Click on copy something with a block that emit light
3. now do paste and place the volume copied
4. See error in the game by night 

i hope can be solved with massive projects can be lost a lot of time 

here an ingame  screenshot that show the bug and others bugs that i report after 

![2021-09-24_15 50 39](https://user-images.githubusercontent.com/91331773/134690898-bac4a33b-6101-4fe3-97a7-d68ede71d5e5.png)

**Comment by gentlegiantJGC** [comment] 2021-10-06 15:40
This is a duplicate of #44

**Closed by gentlegiantJGC** 2021-10-06 15:40 UTC
