### ISSUE TITLE
[Bug Report] Cannot read version 1.1 maps

### ISSUE THREAD

**Issue by aquirin** [Amulet-Team/Amulet-Map-Editor#715] opened 2022-06-21 21:21 UTC
## Bug Report

Cannot read maps from Minecraft 1.1 (neither creative mode nor survival mode). Other maps (for instance, downloaded from: https://www.minecraftmaps.com/popular-maps) are working fine, so it is not a problem with Python.

Python version: 3.7.1

This test does not work:

```
import amulet
map_path = "../maps/TEST" # Extracted from Minecraft v1.1
level = amulet.load_level(map_path)

o = level.chunks
li = o.all_chunk_coords('minecraft:overworld')
len(li) # Produce: 0

li = level.all_chunk_coords('minecraft:overworld')
len(li) # Produce: 0

# Produce: ChunkDoesNotExist exception
level.get_chunk(0, 0, "minecraft:overworld")
```

However, using NBT we can see some data:

```
import amulet_nbt

# Load binary NBT
nbt_obj = amulet_nbt.load("../maps/TEST/data/map_0.dat")

# Produce:
# [0B, ..., 4B, 6B, ..., 49B, 48B, 48B, 49B, 48B, 49B, 48B]
```

### Current Behaviour:

The file looks like empty.

### Expected behavior:

See some chunk content

### Steps To Reproduce:

See code above

### Environment:

- OS (docker container): Linux gaarv-jupyter-keras3 3.10.105 #25426 SMP Mon Dec 14 18:45:24 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
- Minecraft Platform: Java
- Minecraft Version: 1.1
- Amulet Version: amulet-core==1.8.1, amulet-nbt==1.2.1

**Comment by gentlegiantJGC** [comment] 2022-06-21 21:28
We don't support Java worlds before 1.12

**Comment by aquirin** [comment] 2022-06-21 22:20
Ok! This is definitively a pity, but thanks for the fast reply, i was
trying something else, and was not successful either.


Le mar. 21 juin 2022 à 23:29, gentlegiantJGC ***@***.***> a
écrit :

**Comment by gentlegiantJGC** [comment] 2022-06-26 13:48
I am going to close this as a duplicate of #521

**Closed by gentlegiantJGC** 2022-06-26 13:48 UTC
Labels: type: enhancement, priority: low
