### ISSUE TITLE
Problem with using vertical rotation ( ry ) on a .schematic file

### ISSUE THREAD

**Issue by JaymzLkLr** [Amulet-Team/Amulet-Map-Editor#221] opened 2021-03-19 01:32 UTC
This is my first time ever reporting a bug on anything.....so bear with me:

When inserting a schematic file into my world, I'll place it where I want it & then I'll use ry to rotate it vertically to whatever direction I want it. When I do that, certain blocks such as stairs & window panes "stick" to that certain position. I do not have Copy air, water or lava ticked. I've included 4 screenshots to illustrate what I mean. The first two pics (01 & 02) are how it is supposed to be. Pics 03 & 04 is what happens to certain blocks such as stairs when I vertically rotate. I haven't tried any other "schematic" files......these are old .schematic files that I've had for a few years & used to load them in MCedit Unified.

![01](https://user-images.githubusercontent.com/80057455/111718473-5a510900-8830-11eb-840d-3981a4374749.png)
![02](https://user-images.githubusercontent.com/80057455/111718476-5ae99f80-8830-11eb-880c-a2d099d1120d.png)
![03](https://user-images.githubusercontent.com/80057455/111718477-5b823600-8830-11eb-8b82-98cfd3108ca1.png)
![04](https://user-images.githubusercontent.com/80057455/111718480-5c1acc80-8830-11eb-9a11-7ecf2b764180.png)

**Comment by gentlegiantJGC** [comment] 2021-03-21 15:37
duplicate of #74

**Closed by gentlegiantJGC** 2021-03-21 15:37 UTC
