### ISSUE TITLE
1.17 pre-release version doesn't load chunk

### ISSUE THREAD

**Issue by melodiaCaldina** [Amulet-Team/Amulet-Map-Editor#306] opened 2021-05-31 16:46 UTC
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
When trying to load a world generated on version 1.17 (versions 1.17 pre1, 1.17 pre2 or snapshot 21w08b at least), The world is not loading.
error in the console is the following : 
`2021-05-31 18:39:59,374 - amulet_core - ERROR - Error loading chunk -10 6 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 409, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 452, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 222, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 2718)`
(and appear for each chunk)

**To Reproduce**
1. Create a world in one of the 1.17 version on Minecraft
2. Save it
3. Open it with Amulet, version 0.8.5 or 0.8.6b0

**Expected behavior**
The world load nicely and without error

**Screenshots**
![bug Amulet](https://user-images.githubusercontent.com/51825864/120222545-669a0f00-c240-11eb-8886-7dc647ed94ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Amulet Version : Tested on 0.8.5 and Beta 0.8.6b0

**Comment by gentlegiantJGC** [comment] 2021-05-31 16:55
Please search the bug tracker to see if your issue has already been reported.
This is a duplicate of #167

**Closed by gentlegiantJGC** 2021-05-31 16:55 UTC
