### ISSUE TITLE
[Feature Request] Support for vanilla structure files (nbt)

### ISSUE THREAD

**Issue by vico93** [Amulet-Team/Amulet-Map-Editor#935] opened 2023-07-03 02:30 UTC
Why not add support for the vanilla [structure file format](https://minecraft.fandom.com/wiki/Structure_Block_file_format)? Having import/export support for that natively would make setup of custom datapack structures faster (instead of need to export to schematic/construction and the use another thing like worldedit to "convert" to .nbt).

**Comment by gentlegiantJGC** [comment] 2023-07-03 07:43
Duplicate of #385

**Closed as completed by gentlegiantJGC** 2023-07-03 07:43 UTC
Labels: type: enhancement, state: triage
