### ISSUE TITLE
Water chunk dissapear when use resize tool

### ISSUE THREAD

**Issue by EuclidesEngineer** [Amulet-Team/Amulet-Map-Editor#311] opened 2021-06-07 20:26 UTC
I was trying to make a big world 3x sized using the resize chunk, I pasted a big zone, all looks ok except the water zones where it looks like is missing a top part of the sea in some places.
![image](https://user-images.githubusercontent.com/73793694/121083175-16293100-c7ad-11eb-8db9-e52c0d1a01a0.png)

**Comment by gentlegiantJGC** [comment] 2021-06-07 20:55
This is a duplicate of #291

**Closed by gentlegiantJGC** 2021-06-07 20:55 UTC
