### ISSUE TITLE
[Feature Request] Light would disapear after operations

### ISSUE THREAD

**Issue by CrimsonAuditore** [Amulet-Team/Amulet-Map-Editor#866] opened 2023-01-13 07:39 UTC
### Feature Request
**The Problem**
Light of structure would be set to 0 after an operation like movement,paste and cut,the area remain irregular dark even through skylight change like this.
![K`OH8}26J}57`B IMB0IZ7U](https://user-images.githubusercontent.com/65887551/212260255-941df44a-658c-443d-a82b-ea3587d0cf64.png)
**Feature Description**
When saving numrous operations,the light of changed chunks should be reset correctly to avoid extra adjustment in the wold when act Steve.
**Additional context**
I had already spent a host of time reseting light of the area after using Amulet,it remind me that there is a necessary function ever existed in old mcedit.Amulet have done well since I finally found it for architecture in recent Minecraft versions,looking forward to a better Amulet coming soon.

**Comment by gentlegiantJGC** [comment] 2023-01-14 09:25
Duplicate of #44

**Closed as completed by gentlegiantJGC** 2023-01-14 09:25 UTC
Labels: type: bug, state: triage
