### ISSUE TITLE
[Bug Report] Chunks not appearing in 3D editor and being deleted upon next load

### ISSUE THREAD

**Issue by trolliant** [Amulet-Team/Amulet-Map-Editor#721] opened 2022-06-25 16:38 UTC
### Current Behaviour:
Some chunks don't appear in the 3D editor and once being loaded in the editor for the first time, it removes all player placed blocks

### Expected behavior:
Amulet 3D editor should show chunks correct and not delete blocks.

### Steps To Reproduce:

1. Open a world in Minecraft: Bedrock Edition
2. Close Minecraft and then open that world in the Amulet 3D editor
3. Some of the chunks are missing
4. Go back in that world on Minecraft; Bedrock Edition and player placed blocks are gone.

### Environment:

- OS: Windows 11
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19.2
- Amulet Version: 0.9.6

### Screenshots
Before opening in Amulet 3D editor:
![image](https://user-images.githubusercontent.com/74420536/175782722-4fe68515-d2e2-4aac-b1c8-aed702209226.png)

In Amulet 3D editor:
![image](https://user-images.githubusercontent.com/74420536/175782740-afff80b2-e87f-4fac-80bb-4496b5b5d793.png)

After opening Amulet 3D editor:
![image](https://user-images.githubusercontent.com/74420536/175782745-9c94d940-5506-4399-b9bd-88c79539efb5.png)

### Worlds
Link removed

**Comment by StealthyExpertX** [comment] 2022-06-25 17:05
@trolliant You should probably change the title of your bug report to better explain the issue.

**Comment by trolliant** [comment] 2022-06-25 17:30
> @trolliant You should probably change the title of your bug report to better explain the issue.

I've done that now.

**Comment by jwhs123** [comment] 2022-06-26 05:46
Also having this issue except mine will upload them back to the map completely empty just as seen in the editor.
<img width="895" alt="same issue" src="https://user-images.githubusercontent.com/100049199/175801201-dbe961dd-eaa4-4acd-8364-863e77673012.PNG">

**Comment by trolliant** [comment] 2022-06-26 09:10
> Also having this issue except mine will upload them back to the map completely empty just as seen in the editor. <img alt="same issue" width="895" src="https://user-images.githubusercontent.com/100049199/175801201-dbe961dd-eaa4-4acd-8364-863e77673012.PNG">

This is the issue that I am having too, where it uploads the deleted chunks.

**Comment by gentlegiantJGC** [comment] 2022-06-26 14:00
Bedrock made some changes in recent versions that means that chunks only get saved if they change which means it looks like a random mess in the editor.
Usually this is solved by going back into game and placing blocks in the chunks to force the game to save them.

That looks to be the case with the latter image but the original report has chunks with modifications to them.

**Comment by gentlegiantJGC** [comment] 2022-06-26 14:21
Having downloaded this it looks like the world is a marketplace world.
We don't support opening these worlds although it is interesting that Amulet was able to for the most part.
I think the issue is independent of the marketplace world though.

It looks like for some reason part of the leveldb database has been moved into a subdirectory called `lost` which means Amulet cannot access it.

I have seen something like this before. I guess I need to fix the database and include the lost directory in that.

I will remove the download link so that we are not rehosting marketplace content even though the game still requires you to download the pack to play it.

**Comment by gentlegiantJGC** [comment] 2022-06-26 14:31
Did not mean to close this

**Closed** 2022-07-03 12:47 UTC
Labels: type: bug, priority: high
