### ISSUE TITLE
[Feature Request]Biome Replacement

### ISSUE THREAD

**Issue by D15F16UR3D** [Amulet-Team/Amulet-Map-Editor#807] opened 2022-10-14 03:54 UTC
### The Problem
Amulet won´t detect what biome de selected column is

### Feature Description
This Feature Will allow to select an area with different biomes and be able to replace one with another
Example: in the selected area i have desert, jungle and swamp, and i want to replace the desert area with forest but leave intact de other 2

###Alternative
For Worlds up to 1.11 you could use biome painter for this but it was no longer updated when the world format changed

**Comment by gentlegiantJGC** [comment] 2022-10-15 10:26
Duplicate of #435

**Closed as completed by gentlegiantJGC** 2022-10-15 10:26 UTC
Labels: type: enhancement, state: triage
