### ISSUE TITLE
[Bug Report] Crashed during conversion

### ISSUE THREAD

**Issue by jrodr10** [Amulet-Team/Amulet-Map-Editor#651] opened 2022-04-25 00:41 UTC
### Current Behaviour:

did not finish convert only half the spawn is there
### Expected behavior:

full convert of Java 1.18.x world to Bedrock 1.18.30 world
### Environment:

- OS: Windows 
- Minecraft Platform: Java | Bedrock 
- Minecraft Version: 
- Amulet Version: Latest

**Comment by gentlegiantJGC** [comment] 2022-04-26 08:57
Are there any bugs in the console?
Which version of Amulet are you using?

**Comment by gentlegiantJGC** [comment] 2022-04-30 19:44
I think this is a duplicate of #563

**Closed by gentlegiantJGC** 2022-04-30 19:44 UTC
Labels: type: bug, state: more information needed, priority: medium
