### ISSUE TITLE
Bedrock renders further than the chunks it writes to disk

### ISSUE THREAD

**Issue by neomaximus2k** [Amulet-Team/Amulet-Map-Editor#170] opened 2021-02-08 18:05 UTC
Loaded up a map and when "roaming around" I noticed huge areas were not loading in.  Once I saved the file and loaded it in Minecraft the areas get blanked out (see screenshot)

![image](https://user-images.githubusercontent.com/7868678/107262237-31bb3f80-6a38-11eb-8263-f5c81a6186c1.png)

**Comment by gentlegiantJGC** [comment] 2021-02-08 18:12
Which game version?

**Comment by neomaximus2k** [comment] 2021-02-08 18:21
1.16.201.2.0 bedrock

**Comment by gentlegiantJGC** [comment] 2021-02-20 17:33
I don't really understand what the issue is. Did the chunks you are looking at exist before you edited them in Amulet?
The black squares you are looking at are chunks that do not exist. If you explore them in game they will get generated by the game.

**Comment by neomaximus2k** [comment] 2021-02-23 08:43
Yes they did, they were there in the world but once the world loaded up in Amulet they had gone

**Comment by gentlegiantJGC** [comment] 2021-02-23 08:50
Bedrock only saves chunks within a small radius of the player despite rendering much further.
Could it be that they were never actually saved by the game?

**Comment by gentlegiantJGC** [comment] 2021-03-03 10:54
I think what I said is probably the issue. I am going to close this

**Closed** 2021-03-03 10:55 UTC
Labels: more information needed
