### ISSUE TITLE
[Bug Report] Your Title Here

### ISSUE THREAD

**Issue by MisterKreker** [Amulet-Team/Amulet-Map-Editor#680] opened 2022-05-15 09:22 UTC
## Bug Report
C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current
Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 157, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 84, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 130, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 229, in enable
wx._core.wxAssertionError: C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version: 

### Screenshots
![image](https://user-images.githubusercontent.com/105585067/168465945-03a3bb00-409c-407c-bb58-509d92a1648f.png)

**Comment by gentlegiantJGC** [comment] 2022-05-15 09:35
This is fixed in 0.10.
Duplicate of #402 
Until 0.10 is released you can avoid this error by not switching tabs while the editor is loading.

**Closed by gentlegiantJGC** 2022-05-15 09:35 UTC
Labels: type: bug, state: triage
