### ISSUE TITLE
[Feature Request] Search by block name.

### ISSUE THREAD

**Issue by Moltresrider** [Amulet-Team/Amulet-Map-Editor#1044] opened 2024-05-02 12:27 UTC
### The Problem
The map editor lacks a way to search for blocks within the map, such as white concrete and purple wool.

Map viewers and editors seem to lack this feature, which should be a standardized feature in Minecraft map programs.

I am unable to locate my underground house as a result

### Feature Description
Adding an option to search for a specific block by name.
Ideally, the program would display a list of results of where that block/object is located.
Perhaps a "jump to location" could also be added

### Alternatives
I tried both Amulet and Unmined to look for this underground house that I built with white concrete. 

### Additional context
It seems that the editor swears to Arceus that the underground house along with the lanterns that I strung throughout a certain cave do not exist when I KNOW that they ARE there

**Comment by gentlegiantJGC** [comment] 2024-05-06 10:05
Duplicate of #320

**Closed as completed by gentlegiantJGC** 2024-05-06 10:05 UTC
Labels: type: enhancement, state: triage
