### ISSUE TITLE
Impossible to import large .construction

### ISSUE THREAD

**Issue by FluffyDiscord** [Amulet-Team/Amulet-Map-Editor#104] opened 2020-09-08 21:01 UTC
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**
Similar to: https://github.com/Amulet-Team/Amulet-Map-Editor/issues/89

**Describe the bug**
Loading large .construction files (2500x250x2500) ends up after few hours in infinite loop of "program seems fine and then it hangs again and again". Program uses all available RAM (which is fine), but it eats every single MB I have (32GB system RAM, the program was using over 26GB alone at some point), possibly causing some errors due to being on low RAM(?) (nothing in console), thus getting stuck.

**To Reproduce**
1. Load any map (my was 10k pregenerated world)
2. Import .construction

**Expected behavior**
Imports properly (finishes), even if it takes long, instead of being stuck in a loop.

**Screenshots**
Don't be fooled by that time, it has been over 4 hours, since I started. Still waiting in vain.
![image](https://user-images.githubusercontent.com/10332247/92527215-f6b5a580-f226-11ea-9732-78075cedde92.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64x build 2004
 - Amulet: V0.7.0.1

**Additional context**
I did notice that after few hours the RAM usage dropped to stable 15GB and that the rendered map at the background somewhat updated, but the import window is still stuck in with that infinite hanging problem.

**Comment by gentlegiantJGC** [comment] 2020-09-10 14:26
It first loads the structure and then creates all the geometry for it. This was a quick fix and wasn't designed for large structures.
This is a duplicate of #92

**Closed by gentlegiantJGC** 2020-09-10 14:26 UTC
