### ISSUE TITLE
[Critical] Lighting Bug from .construction import.

### ISSUE THREAD

**Issue by Cixon** [Amulet-Team/Amulet-Map-Editor#214] opened 2021-03-14 08:27 UTC
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
The lighting copied the day/night cycle?

**To Reproduce**
1. Download latest [ v0.8.1a16 ]
2. Import a .construction file.
3. See bug.

**Expected behavior**
Not bizarre behavior like the screenshots below.

**Screenshots**
![Screenshot (127)](https://user-images.githubusercontent.com/69068153/111062229-39be3300-846d-11eb-9d25-015e2c9be27f.png)
![Screenshot (128)](https://user-images.githubusercontent.com/69068153/111062230-3aef6000-846d-11eb-81ad-538d7372409c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 20H2

**Additional context**
Was using a world with modded assets.
A mod that may have caused the issue include:
[Oh the Biomes Youll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)

**Comment by Cixon** [comment] 2021-03-14 08:36
Here's the .construction that caused the problem:
https://drive.google.com/file/d/151tmpJ9ML0hTCX7XR5AKCkOGGGbwRiva/view?usp=sharing

**Comment by Cixon** [comment] 2021-03-14 08:42
I'd love a workaround or perhaps a integration in the editor that will fix the bug for me, perhaps scans for bizarre lighting or something similar, not sure.

I don't mind re-importing it but the issue is time for me. I'd love to see this fixed!

**Comment by gentlegiantJGC** [comment] 2021-03-14 08:53
duplicate of #44 #60

**Closed by gentlegiantJGC** 2021-03-14 08:53 UTC

**Comment by Cixon** [comment] 2021-03-14 08:57
dang. well is there any way around this?
