### ISSUE TITLE
Requirements not installed in order and build deps not installed at all on ubuntu 18.04, resulting in failure as a build dependency is not found during build time

### ISSUE THREAD

**Issue by juozaspo** [Amulet-Team/Amulet-Map-Editor#1] opened 2019-12-01 13:21 UTC
Trying to install requirements inside a python 3.7 ENV created on Ubuntu Linux 18.04 fails with error that says numpy is not installed. The cause is wrong installation order and build deps not getting installed at all.
```
(ENV) juozas@xubuntu:~/test/Amulet-Map-Editor$ pip install -r requirements.txt 
Collecting git+git://github.com/Amulet-Team/Amulet-NBT.git (from -r requirements.txt (line 3))
  Cloning git://github.com/Amulet-Team/Amulet-NBT.git to /tmp/pip-ehwuzupq-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ehwuzupq-build/setup.py", line 13, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ehwuzupq-build/
```
There should be a note in documentation that user might need to update pip and setuptools if using ENV method to build and install dependencies for running gui. Like noted in Amulet-Team/Amulet-Core#60 `python3.7-dev` should be installed too as it is needed to build of one of requirements found in requirements file. Also `libgtk-3-dev` is required to build wxPython, w/o that build might fail with another error.
A workaround for pip installation order problem where git submodules gets installed first would be running command `cat requirements.txt | xargs -I{} sh -c 'pip install {}'` instead of `pip install -r requirements.txt` while inside the ENV, build deps installation problem is fixed by updating pip and setuptools.
Otherwise to check for other outdated packages, make sure pip is upgraded first then run `pip list -o` as I described in https://github.com/Amulet-Team/Amulet-Core/issues/60#issuecomment-560364760
 
**Edit:** Completely rewrote description, removed old garbage left from earlier testing and added a workaround for pip installation order problem.
**Edit2:** added note how to check for and update old python packages, might be helpful.
**Edit3:** Updated pip output to reflect current state of repository.

**Comment by Ex-Ark** [comment] 2019-12-01 13:55
Encountered the same problem : `libgtk-3-dev` is in fact required, as well as `libpng12` and `libjpeg-8` (later on as run time dependencies), problem is on some newer distribution (like debian 10 buster) these packages are no longer valid installation candidate.
I had to download and `dpkg -i` manually install these packages.

I myself have a windows OS and managed to run the GUI inside an unix container, and share the DISPLAY variable so I have the GUI opening on my host OS.

Take a look here : 
https://gist.github.com/Ex-Ark/1d580aaccb03bca7417584902988badd

**Comment by juozaspo** [comment] 2019-12-01 14:47
Build completed. It can be run using python amulet-tech-demo-ui.py while inside env. The main window loads. `Select World` button works (choosing file from dialog untested), `Open World` button throws error
```
python amulet-tech-demo-ui.py 
Traceback (most recent call last):
  File "amulet-tech-demo-ui.py", line 50, in __init__
    self._world = world_interface.load_world(world_path)
  File "/home/juozas/test/Amulet-Map-Editor/ENV/lib/python3.7/site-packages/amulet/world_interface/__init__.py", line 18, in load_world
    return World(directory, load_format(directory, _format, forced))
  File "/home/juozas/test/Amulet-Map-Editor/ENV/lib/python3.7/site-packages/amulet/world_interface/__init__.py", line 32, in load_format
    if not os.path.isdir(directory):
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
Maybe the button should be disabled until world is selected? Selecting a minecraft World directory (containing files/folders `advancements,data,datapacks,DIM1,DIM-1,icon.png,level.dat level.dat_old,playerdata,poi,region,session.lock,stats`) throws another error
```
Traceback (most recent call last):
  File "amulet-tech-demo-ui.py", line 50, in __init__
    self._world = world_interface.load_world(world_path)
  File "/home/juozas/test/Amulet-Map-Editor/ENV/lib/python3.7/site-packages/amulet/world_interface/__init__.py", line 18, in load_world
    return World(directory, load_format(directory, _format, forced))
  File "/home/juozas/test/Amulet-Map-Editor/ENV/lib/python3.7/site-packages/amulet/world_interface/__init__.py", line 48, in load_format
    format_class = formats.loader.get(directory)
  File "/home/juozas/test/Amulet-Map-Editor/ENV/lib/python3.7/site-packages/amulet/world_interface/loader.py", line 104, in get
    object_id = self.identify(identifier)
  File "/home/juozas/test/Amulet-Map-Editor/ENV/lib/python3.7/site-packages/amulet/world_interface/loader.py", line 116, in identify
    raise LoaderNoneMatched(f"Could not find a matching {self._object_type}")
amulet.api.errors.LoaderNoneMatched: Could not find a matching format
```

**Comment by juozaspo** [comment] 2019-12-01 19:35
`cat requirements.txt | xargs -I{} pip install {}` command can also be used if pip does not install requirements in order. By using that there are less problems encountered during deps installation

**Comment by Podshot** [comment] 2019-12-02 01:59
Did updating the pip installation in the virtual environment also resolve this issue?

**Comment by juozaspo** [comment] 2019-12-02 05:25
Updating pip might have fixed it, as it now installs build dependencies for git objects, not sure about the installation order, as it is still not in proper oder.

**Comment by juozaspo** [comment] 2019-12-02 12:24
The problem is outdated setuptools package. Not having the latest version can bring out many problems. To avoid that setuptools and pip must be upgraded. To check for other outdated packages, make sure pip is upgraded first then run `pip list -o` as I described in https://github.com/Amulet-Team/Amulet-Core/issues/60#issuecomment-560364760

**Comment by Podshot** [comment] 2019-12-03 19:22
It does indeed seem to be a weird issue between pip/setuptools. I've tried to replicate this issue on multiple new virtual environments but I'm not able to produce this issue. I feel that our installations instructions are the best they can be, since we can't account for every weird and unexpected issue that might come up with pip/setuptools, without being too complex or too in-depth.

In addition, after talking with the rest of the team, we will be removing the setup instructions for this repository for now since all of the code is still in the prototype/tech demo stage and not in a suitable stable/working state. We will be leaving the Amulet-Core instructions present in that repository for those who wish to run the unittests and take a look at the core API.

**Comment by Podshot** [comment] 2019-12-07 04:32
Further investigation resulted in that this is caused by dependencies not being installed even though they are marked as required for package setup to be ran, thus the `ImportError`. While this is a pip issue since it’s ignoring a setup argument, I believe we can to rework our version file to fix this issue, so I’m reopening this.

I’m sorry we didn’t catch that the first time, I’ll let you know when I believe the issue is resolved and I’ll ask that you try your installation process again to see if it is indeed fixed if you wish to do so.

**Comment by juozaspo** [comment] 2019-12-07 10:47
Tested in a bare minimum ubuntu 18.04 environment set up in vm, still not going past numpy after upgrading pip and setuptools. It appears it's not only my main configuration is affected so this must be a pip or other obscure bug.

**Comment by juozaspo** [comment] 2019-12-07 17:12
Confirmed on Xubuntu 18.04.3 Live CD. Fails as numpy is not found.
```
(ENV) xubuntu@xubuntu:~/Amulet-Map-Editor$ pip install -r requirements.txt 
Collecting git+git://github.com/Amulet-Team/Amulet-NBT.git (from -r requirements.txt (line 3))
  Cloning git://github.com/Amulet-Team/Amulet-NBT.git to /tmp/pip-umw5wgx9-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-umw5wgx9-build/setup.py", line 13, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-umw5wgx9-build/
```
Packages installed prior creating env, installed using `sudo apt-get install --no-install-recommends <package>` command:
```
python3.7
python3.7-venv
python3.7-dev
git
python3-distutils
```
P.s. Running vm and installing deps above needs a HELL lot of ram. About 960 MB or more. Otherwise there might be some unforeseen errors even before attempting install those deps (e.g. memory or disk space errors as there's not enough ram)
It's also wise to run `sudo apt-get clean` after each dep installation if there's a disk space error during next dep install (before setting up env and running pip inside it).

**Comment by Podshot** [comment] 2019-12-15 15:55
I'm not able to reproduce that issue on our TravisCI pipeline, but you can manually install `Amulet-NBT` from it's release page [here](https://github.com/Amulet-Team/Amulet-NBT/releases/tag/1.0.2). As for the other issues, we've reworked how our `setup.py` scripts work and the process should be less of a headache now.

As for the RAM amount, it's out of our control and there's no way we can change that. If you have any other issues, feel free to post a follow-up comment and I'll reopen the issue if necessary.

**Closed by Podshot** 2019-12-15 15:55 UTC
Labels: OS/Linux, bug

**Comment by Mhowser** [comment] 2020-12-07 04:12
I'm on ubuntu 18.04 and i'm trying to install from source by doing `python -m pip install amulet-map-editor==0.7.2.8` and it is failing due to missing header file 'python.h', even though I have `python3-dev` installed. 

here the part where it failed
```
 /usr/bin/python setup-wxsvg.py build_ext --inplace
    Compiling wx/svg/_nanosvg.pyx because it depends on /home/cosmocrat/.local/lib/python3.7/site-packages/Cython/Includes/cpython/buffer.pxd.
    [1/1] Cythonizing wx/svg/_nanosvg.pyx
    running build_ext
    building 'wx.svg._nanosvg' extension
    creating build/wxsvg
    creating build/wxsvg/temp.linux-x86_64-3.7
    creating build/wxsvg/temp.linux-x86_64-3.7/wx
    creating build/wxsvg/temp.linux-x86_64-3.7/wx/svg
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -g -fdebug-prefix-map=/build/python3.7-OVQonc/python3.7-3.7.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNANOSVG_IMPLEMENTATION=1 -DNANOSVGRAST_IMPLEMENTATION=1 -DNANOSVG_ALL_COLOR_KEYWORDS=1 -Iext/nanosvg/src -I/usr/include/python3.7m -c wx/svg/_nanosvg.c -o build/wxsvg/temp.linux-x86_64-3.7/wx/svg/_nanosvg.o
    wx/svg/_nanosvg.c:37:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Command '/usr/bin/python setup-wxsvg.py build_ext --inplace' failed with exit code 1.
    Finished command: build_others (0m1.205s)
    Finished command: build_py (19m51.16s)
    Finished command: build (27m46.381s)
    Command '"/usr/bin/python" -u build.py build' failed with exit code 1.
```
how can I fix this?

**Comment by Podshot** [comment] 2020-12-07 05:50
@Mhowser Are you using your system's python or the `python3-dev` that you have installed?

**Comment by Mhowser** [comment] 2020-12-07 10:45
I'm pretty sure its using the system's python, how do I force it to use
python3-dev?
