### ISSUE TITLE
[Feature Request] Your Title Here

### ISSUE THREAD

**Issue by Tomoko2020** [Amulet-Team/Amulet-Map-Editor#744] opened 2022-07-13 08:50 UTC
### The Problem
When copying Chunks, It would be nice to have a chunk lock and sea level lock options for the paste command, or something close to them

### Feature Description
Being able to lock onto already existing chunks or rather where chunks should be far from spawn and being able to use the paste option with it so there isn't empty space into the void or be too elevated or lowered

### Alternatives
Alternatively all I do is put chunks down and try to line them up the best I can

### Additional context
The void is annoying lol

**Comment by gentlegiantJGC** [comment] 2022-07-13 12:23
Looks like a duplicate of #720

**Closed as completed by gentlegiantJGC** 2022-07-13 12:23 UTC
Labels: type: enhancement, state: triage
