### ISSUE TITLE
World doesn't render properly (AMD issue?)

### ISSUE THREAD

**Issue by Wapply** [Amulet-Team/Amulet-Map-Editor#415] opened 2021-09-15 15:28 UTC
Windows 10 Pro (2004)
CPU: i7 4790k
GPU: AMD R7 260x (21.3.1)
RAM: 8GB

https://user-images.githubusercontent.com/88293580/133462896-fe756242-bc66-4408-9535-d970b5bf4579.mp4

**Comment by gentlegiantJGC** [comment] 2021-09-15 16:04
This is a duplicate of #405

**Closed by gentlegiantJGC** 2021-09-15 16:04 UTC
