### ISSUE TITLE
The UI is very glitchy and the world did not open properly (Linux)

### ISSUE THREAD

**Issue by Belugaking** [Amulet-Team/Amulet-Map-Editor#317] opened 2021-06-09 23:20 UTC
**Description**
I opened the application and was greeted with a glitchy UI that would keep appearing and disabling at a rapid rate whenever my cursor gets close to the edge of the viewport making it unusable. Also I loaded a world from Minecraft 1.17 and 1.16.5 in it and it did not load the world properly I just saw a void of blue.

**Expected behavior**
1. Build application from source.
2. Run it and open a world from Minecraft.

![image](https://user-images.githubusercontent.com/20518757/121440977-ed449f80-c956-11eb-959f-fdba493656b9.png)

**Desktop**
OS: Manjaro Linux XFCE
Version: 5.12.8-1

**Comment by gentlegiantJGC** [comment] 2021-06-10 06:54
Duplicate of #127 
Please use the search tool

**Closed by gentlegiantJGC** 2021-06-10 06:54 UTC
