### ISSUE TITLE
[Bug Report] Editor not rendering worlds

### ISSUE THREAD

**Issue by Sot-Mits** [Amulet-Team/Amulet-Map-Editor#881] opened 2023-03-12 16:01 UTC
### Current Behaviour:

Program renders a blank world even when in game it looks fine

### Expected behavior:

The program should render the world as expected

### Steps To Reproduce:

Launch program from terminal
Choose (Java) world to open

### Environment:

- OS: OSX (Intel-based)
- Minecraft Platform: Java 
- Minecraft Version: 1.19.3 (forge 44.1.0)
- Amulet Version: v.0.9.6

### Additional context

None of the mods affect any world/entity data, just enhancements like JEI and Sodium
Screenshots are from both respective worlds

The program also throws an error about SSL Cerificates and promts to run 'Install Certificates.command' despite already having done so

### Screenshots

<img width="1440" alt="Screenshot 2023-03-12 at 16 51 11" src="https://user-images.githubusercontent.com/86083227/224556844-7e505731-7409-4645-9991-aaf38df56ece.png">
<img width="1440" alt="Screenshot 2023-03-12 at 16 55 57" src="https://user-images.githubusercontent.com/86083227/224556873-91cdb21f-1a19-4d38-8531-5ff399511d24.png">

### Worlds

[Skyblock 2.1.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/10951365/Skyblock.2.1.zip)
[New World 2.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/10951367/New.World.2.zip)

**Comment by gentlegiantJGC** [comment] 2023-03-29 09:54
Both of the worlds you have sent load and display correctly on my computer.
The first image is because the texture pack had not downloaded.
Please can you send the log file for the second level so I can see what is going wrong.

**Comment by fury23711** [comment] 2023-06-02 19:03
i have the same problem with the resource pack not downloading. 
![Desktop Screenshot 2023 06 02 - 13 50 40 00](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/135377649/27219398-5141-4824-b594-c78860ade12f)


![Desktop Screenshot 2023 06 02 - 14 01 30 54](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/135377649/727b10e6-da19-420a-bc37-5225c9976f11)

**Comment by gentlegiantJGC** [comment] 2023-06-03 09:57
I am going to close this as a duplicate of #419

**Closed as completed by gentlegiantJGC** 2023-06-03 09:57 UTC
Labels: type: bug, state: more information needed, priority: high
