### ISSUE TITLE
Empty inventories when converting a world

### ISSUE THREAD

**Issue by MagnoBooter** [Amulet-Team/Amulet-Map-Editor#256] opened 2021-04-13 21:45 UTC
**Describe the bug**
When converting a LevelDB world to a Anvil format world, all inventories are empty, all items are gone.

**To Reproduce**
Convert a world whose inventories have items, e.g. a chest.
The chest will be empty in the output world.

**Expected behavior**
All inventories should contain whatever was there in the input world.

**Screenshots**
The original chest in the LevelDB world:
![Screenshot from 2021-04-13 23-40-28](https://user-images.githubusercontent.com/3240114/114624891-b2552100-9cb1-11eb-8c5b-a1048e4986d7.png)
After conversion to Anvil format:
![Screenshot from 2021-04-13 23-37-31](https://user-images.githubusercontent.com/3240114/114624895-b5e8a800-9cb1-11eb-8c0f-32a6d752c50e.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: master branch as of 2021-04-12

**World details**
- Input world originated from a vanilla 1.16.201.02 bedrock server
- Output world to a Paper server with Multiverse and WorldEdit.

**Additional context**

**Comment by gentlegiantJGC** [comment] 2021-04-14 09:39
duplicate of #155

**Closed by gentlegiantJGC** 2021-04-14 09:39 UTC
