### ISSUE TITLE
Amulet fails to load saved world on PopOS/Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by bokov** [Amulet-Team/Amulet-Map-Editor#1095] opened 2024-08-19 07:53 UTC
### Current Behaviour:

After installing Amulet map editor on Ubuntu Linux 20.04 LTS and successfully getting to the main screen, I load a saved world then click '3D Editor' in the left sidebar. The app shows a download java resources progress bar and then exits. The console log is as follows:

```
INFO - Loading level /home/a/.minecraft/saves/Up House
INFO - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO - Downloading java launcher manifest file.
INFO - Finished downloading java launcher manifest file.
INFO - Downloading Java resource pack for version 1.21.1
**
Pango:ERROR:../pango/pango-layout.c:4192:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
Bail out! Pango:ERROR:../pango/pango-layout.c:4192:pango_layout_check_lines: assertion failed: (!layout->log_attrs)

```     

### Expected behavior:

Opening the saved (Java 1.19.3) world for editing.

### Steps To Reproduce:

As above. I tried other saves and got the same result.

### Environment:

- OS:  linux, Pop!_OS 20.04 LTS (but for our purposes it's almost identical to Ubuntu)
- Minecraft Platform: Java 
- Minecraft Version: 1.19.3
- Amulet Version: V0.10.35

**Comment by bokov** [comment] 2024-08-19 07:57
One more thing-- Amulet doesn't try in any way to piggyback on whatever it thinks is the default already-installed version of Minecraft, does it? Because I have several different launchers, with various MC versions, etc. and hopefully Amulet only pays attention to the version of the saved game it's trying to open and downloads whatever it needs based on that alone.

**Comment by bokov** [comment] 2024-08-19 08:05
Update:

I installed PyOpenGL and PyOpenGL_accelerate, which got rid of the 'No OpenGL_accelerate' message but Amulet still crashes when I load a world and then click '3D Editor', with the following messages:

```
INFO - Loading level /home/a/.minecraft/saves/Up House
INFO - OpenGL_accelerate module loaded
INFO - Using accelerated ArrayDatatype
INFO - Downloading java launcher manifest file.
INFO - Finished downloading java launcher manifest file.
INFO - Downloading Java resource pack for version 1.21.1
**
Pango:ERROR:../pango/pango-layout.c:4192:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
Bail out! Pango:ERROR:../pango/pango-layout.c:4192:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
```

**Comment by gentlegiantJGC** [comment] 2024-08-20 06:53
Looks like a duplicate of #1012 



> Amulet doesn't try in any way to piggyback...

No it doesn't

**Closed as completed by gentlegiantJGC** 2024-08-20 06:53 UTC
Labels: type: bug, state: triage
