### ISSUE TITLE
[Feature Request] Compatibility with older Minecraft versions, such as 1.0

### ISSUE THREAD

**Issue by Eevee349** [Amulet-Team/Amulet-Map-Editor#574] opened 2022-02-22 01:27 UTC

**Comment by Eevee349** [comment] 2022-02-22 01:27
and of course nothing I typed worked

**Comment by gentlegiantJGC** [comment] 2022-02-22 07:18
You did not read the first few lines of the template.
I am going to close this as a duplicate of #521

**Closed by gentlegiantJGC** 2022-02-22 07:18 UTC
Labels: enhancement
