### ISSUE TITLE
Lighting Stuck to Full Bright When Converting Backwards

### ISSUE THREAD

**Issue by I967Firebirdz** [Amulet-Team/Amulet-Map-Editor#1079] opened 2024-07-21 00:11 UTC
When I converted my world back to 1.12.2 from 1.21.2.2 all blocks emit level 15 light for no apparent reason making nighttime nonexistent basically.  I tried adjusting settings, working on the code and I can't figure out a way to fix this issue.  Has anyone else run into this or have any idea how to fix it?  This issue did not happen the last time I converted the world back about a year ago, so something changed.  Mods don't affect it because it happens with or without them.

**Comment by I967Firebirdz** [comment] 2024-07-21 04:25
I've found a partial solution to this using MC Edit you can relight chunks.  That said, there are still many that give me errors when I try to relight them.  This is a huge PITA unfortunately.

**Comment by gentlegiantJGC** [comment] 2024-07-22 08:10
Duplicate of #44

**Closed as completed by gentlegiantJGC** 2024-07-22 08:10 UTC
Labels: type: bug, state: triage
