### ISSUE TITLE
[Feature Request] Your Title Here

### ISSUE THREAD

**Issue by ZyberTrack** [Amulet-Team/Amulet-Map-Editor#821] opened 2022-10-31 21:21 UTC
### The Problem
I get a lightning glitch after editing a world. need to relight the chunks, where is the Funktion for this in the WorldEditor?.

### Feature Description
A possibility to relight all chunks of a World

**Comment by gentlegiantJGC** [comment] 2022-11-01 10:19
Duplicate of #44

**Closed as completed by gentlegiantJGC** 2022-11-01 10:19 UTC
Labels: type: enhancement, state: triage
