### ISSUE TITLE
Slabs are not being converted from bedrock to java

### ISSUE THREAD

**Issue by alexlm11** [Amulet-Team/Amulet-Map-Editor#713] opened 2022-06-16 08:51 UTC

**Comment by gentlegiantJGC** [comment] 2022-06-18 14:02
You have provided virtually no information.
Which slabs?
Which versions of bedrock and java?
Which version of Amulet are you using?

**Comment by AnnoyingVillager** [comment] 2022-06-18 15:46
According to what I've known, in some chunks, all type of stone slabs (smooth stone slabs, stone bricks slab, sandstone slab, etc) are not being converted. This happens when converting worlds from Bedrock 1.18.31 to Java 1.18.1 and Bedrock 1.19.0 to Java 1.19
![image](https://user-images.githubusercontent.com/94441745/174446140-b80c149c-551f-437b-ab05-2fbf243516bd.png)
![image](https://user-images.githubusercontent.com/94441745/174446157-1c1eec54-f757-4d4c-9cb0-f9ed67a2be67.png)

**Comment by AnnoyingVillager** [comment] 2022-06-18 15:49
Also in some chunks, sealanterns will not be converted.

**Comment by gentlegiantJGC** [comment] 2022-06-19 08:34
Looks like they changed the block state for slabs. This is a duplicate of #711

**Closed** 2022-06-19 11:46 UTC
Labels: type: bug, state: more information needed, state: triage
