### ISSUE TITLE
[Feature Request] Toggle Chunk Overlay

### ISSUE THREAD

**Issue by VL4DST3R** [Amulet-Team/Amulet-Map-Editor#759] opened 2022-07-25 18:30 UTC
### The Problem
The checkered overlay that renders high in the sky, meant to represent chunks can be very distracting when working with large scale builds where you need to view them from afar.

Toggling it off would be very useful.

### Feature Description
Options > Toggle Chunk Overlay (or a keybind)

### Alternatives
Talking on discord the only "solution" i was offered was to change the texture itself and compile from source. This is hardly convenient.

**Comment by gentlegiantJGC** [comment] 2022-12-21 10:22
Duplicate of #627

**Closed as completed by gentlegiantJGC** 2022-12-21 10:22 UTC
Labels: type: enhancement, priority: low
