### ISSUE TITLE
When moving builds from one world to another villagers and animals are not moved (bedrock to bedrock)

### ISSUE THREAD

**Issue by itadminmynapse** [Amulet-Team/Amulet-Map-Editor#373] opened 2021-07-08 12:40 UTC
when exporting a building from a bedrock world and importing it into another bedrock world (e.g. villager trading hall, pen filled with sheep), the villagers, animals (and mobs?) are not moved over (not exported?)

**Comment by gentlegiantJGC** [comment] 2021-07-08 12:44
We do not currently support entities.
I am going to close this as a duplicate of #171

**Closed by gentlegiantJGC** 2021-07-08 12:44 UTC
