### ISSUE TITLE
Copy/Paste/Rotate issues with stair blocks / walls / trap doors / signs / redstone items

### ISSUE THREAD

**Issue by Jahfry** [Amulet-Team/Amulet-Map-Editor#277] opened 2021-04-27 06:37 UTC
**Describe the bug**
Pasting a structure with stairs / walls / trap doors and then rotating prior to final placement results in the blocks going to some other orientation.

On rotating, stairs always orient incorrectly lose cornering (loss of cornering wasn't a surprise and I'd assume that's almost impossible to address, was understanding I'd need to fix a lot of those). Walls revert to post form even when that form would be impossible based on attachment to adjacent blocks. Trap doors changed from horizontal to vertical when attached as shown. Sign rotated wrong as shown. 

Sticky piston somehow broke? (screenshots). Repeaters/comparators retained original rotation, too, which breaks all mechanisms. 

Looking closer what it looks like happened is not that these are going into a default orientation like I first thought but that *most* are staying in their original orientation when rotated (meaning they're 90deg off). This fits what seems to have happened to walls / fences and maybe stairs. 

It doesn't address the way the trap doors changed, as they swapped from horizontal to vertical. And the sticky pistons, while retaining their original rotation, broke badly and may have partially duplicated?

User error is always a possibility. I'm very new at Amulet. 

**To Reproduce**
1. Create a structure with stair blocks at off-default angles (for edging corners, etc)
2. Open world in Amulet
3. Select structure
4. Copy structure
5. Paste structure
6. Rotate 90deg prior to final placement
7. Save and load into MC

**Expected behavior**
Stair rotates to face the newly rotated angle if angle was a multiple of 90deg. Even if corner roundings can't be calculated it would save a ton of time on large structures to have 50% or more of the stairs facing the expected angle. 

Walls take the form they would based on the blocks they are attached to rather than the default post orientation. 

Trap doors rotate and retain vertical vs horizontal orientation of original placement.

I'd guess other things like repeaters/comparators, etc may have issue

**Screenshots**

Note: all 4 shots taken from same MC save / session after doing the rotation. 

Original orientations first, post-rotation duplicated second. 

![2021-04-26_23 14 06](https://user-images.githubusercontent.com/16520816/116194517-ceab8180-a6e5-11eb-8463-1b391f520df0.png)
![2021-04-26_23 14 24](https://user-images.githubusercontent.com/16520816/116195421-0b2bad00-a6e7-11eb-8f7a-e88d96df802e.png)

![2021-04-26_23 25 15](https://user-images.githubusercontent.com/16520816/116195217-c4d64e00-a6e6-11eb-958c-fd91d41352b9.png)
![2021-04-26_23 25 19](https://user-images.githubusercontent.com/16520816/116195601-4928d100-a6e7-11eb-87af-6afacf5c8478.png)

![2021-04-26_23 30 29](https://user-images.githubusercontent.com/16520816/116196057-db30d980-a6e7-11eb-9e4b-2b706436c0e3.png)
![2021-04-26_23 31 12](https://user-images.githubusercontent.com/16520816/116195989-c6544600-a6e7-11eb-97fe-31a6628639c8.png)

![2021-04-26_23 32 38](https://user-images.githubusercontent.com/16520816/116196094-e97ef580-a6e7-11eb-8b2e-519aecbe2b85.png)
![2021-04-26_23 31 27](https://user-images.githubusercontent.com/16520816/116196148-fd2a5c00-a6e7-11eb-8d48-833728575591.png)

![2021-04-26_23 32 11](https://user-images.githubusercontent.com/16520816/116196269-221ecf00-a6e8-11eb-8fd5-a49531c836cf.png)
![2021-04-26_23 31 53](https://user-images.githubusercontent.com/16520816/116196227-14694980-a6e8-11eb-8849-4a9752089ced.png)

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Version: Java 1.16, no block mods (fabric, shaders, minimap)
 - Amulet Version: 0.8.4 (current release, updated today)

**Additional context**
Lighting also didn't seem to save properly. This is my first run at trying this so I might have goofed that. Had to destroy and replace all lights to get lighting to appear again when using lanterns. 

I'm putting this structure on hold for now in hopes there might be something that helps the situation as fixing every corner in this building will be days (not a complaint, just explaining that waiting won't hurt anything). What I was doing was building 1/4 of a large structure that is identical in all 4 corners and was hoping to simply paste in the original 1/4 structure 3 additional times, rotating each another 90deg. 

I realize I ended up assuming the rotate tool would work with more complicated things than solid blocks and it was my goof :) Filing to have a hope a little longer.

**Comment by gentlegiantJGC** [comment] 2021-04-27 09:04
This is a duplicate of #74
Please use the search tool before reporting bugs

**Closed by gentlegiantJGC** 2021-04-27 09:04 UTC
