### ISSUE TITLE
Chunk/world/selection analyzer

### ISSUE THREAD

**Issue by TheTechn0mancer** [Amulet-Team/Amulet-Map-Editor#377] opened 2021-07-14 17:30 UTC
**Has your feature request already been suggested? Please check if your suggested feature has already been suggested.**
No
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Select a chunk or area and click a button to have the app count the number or percentage of each block in the area. So if I select an area 1000x1x1000 (a huge horizonal slice) it could tell me which blocks are on that layer. Useful for determining optimal mining layers for each kind of block/ore.

**Describe alternatives you've considered**
It would be cool if it could generate (doesn't have to render) a huge radius of thousands of chunks and analyze the whole thing and call it a world seed analyzer. It could break down the world into horizontal slices with interesting data.

**Additional context**
I kinda just want a tool to experimentally determine (using an absolutely huge area) what the ore distribution *actually* is due to other factors such as cave generation and air blocks inhibiting ore generation.

**Comment by gentlegiantJGC** [comment] 2021-07-14 20:25
```
Has your feature request already been suggested? Please check if your suggested feature has already been suggested.
No
```
Please use the search feature before opening a new issue. This is a duplicate of #150

**Closed by gentlegiantJGC** 2021-07-14 20:25 UTC
