### ISSUE TITLE
missing chunks in bedrock world while in editing and after editing

### ISSUE THREAD

**Issue by GGTAYLOR-POG** [Amulet-Team/Amulet-Map-Editor#645] opened 2022-04-18 20:35 UTC
I don't know this much but whenever I  get into the editor  in my Minecraft bedrock world it  deletes chunks  and I  just cant explain it  I  have it on windows and I believe it is the newest version

**Comment by SaleProperly** [comment] 2022-04-19 23:17
I just tried to open a freshly made bedrock world with experimental features and there were chunks missing in the editor.

**Comment by GitHababi** [comment] 2022-04-20 05:13
I just confirmed this is a result of the recent 1.18.30 patch on bedrock.
When I open a world file that is v1.18.12, no missing chunks, but when I update it to 1.18.30, there are various broken and missing chunks.

**Comment by gentlegiantJGC** [comment] 2022-04-23 08:36
We don't support experimental features.
1.18.30 should be supported in Amulet 0.9.1.
If this is still an issue in Amulet 0.9.1 can someone add some more details on what the issue actually is. Do the chunks look black, red or blue? Are there errors in the console?

**Comment by GitHababi** [comment] 2022-04-23 15:24
I just installed v0.9.2 and I think it had to do with an unsupported chunk version as the editor showed it in red.
Screenshot from v0.9.1:
![image](https://user-images.githubusercontent.com/76075036/164912436-a9e91e84-385f-437c-8703-7a9683ff90ed.png)
Screenshot from v0.9.2:
![image](https://user-images.githubusercontent.com/76075036/164912441-2bf3d411-a3b5-4c29-af9f-4854a9680e99.png)

The log states:
`
amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('bedrock', 40)
2022-04-23 08:22:50,937 - amulet_core - ERROR - Error loading chunk 89 -16 minecraft:overworld
Traceback (most recent call last):
  File "amulet\api\wrapper\format_wrapper.py", line 433, in _safe_load
  File "amulet\api\wrapper\format_wrapper.py", line 476, in _load_chunk
  File "amulet\api\wrapper\format_wrapper.py", line 241, in _get_interface_and_translator
  File "amulet\api\wrapper\world_format_wrapper.py", line 67, in _get_interface
  File "amulet\level\loader.py", line 74, in get
  File "amulet\level\loader.py", line 85, in identify
`
But support has since been added, this bug is fixed

**Comment by gentlegiantJGC** [comment] 2022-04-26 08:54
@GGTAYLOR-POG can you confirm if this is the issue you were originally referring to

**Comment by LuisBionic16** [comment] 2022-05-14 01:19
I think I still have this issue and I am running a newer version of Bedrock at the moment.

**Comment by LuisBionic16** [comment] 2022-05-14 01:28
> We don't support experimental features. 1.18.30 should be supported in Amulet 0.9.1. If this is still an issue in Amulet 0.9.1 can someone add some more details on what the issue actually is. Do the chunks look black, red or blue? Are there errors in the console?

I am having this issue and it's a release version

> I just confirmed this is a result of the recent 1.18.30 patch on bedrock. When I open a world file that is v1.18.12, no missing chunks, but when I update it to 1.18.30, there are various broken and missing chunks.

Same, I am also experiencing this. I hope this gets fixed soon.

**Comment by gentlegiantJGC** [comment] 2022-05-14 08:37
> > We don't support experimental features. 1.18.30 should be supported in Amulet 0.9.1. If this is still an issue in Amulet 0.9.1 can someone add some more details on what the issue actually is. Do the chunks look black, red or blue? Are there errors in the console?
> 
> I am having this issue and it's a release version
> 
> > I just confirmed this is a result of the recent 1.18.30 patch on bedrock. When I open a world file that is v1.18.12, no missing chunks, but when I update it to 1.18.30, there are various broken and missing chunks.
> 
> Same, I am also experiencing this. I hope this gets fixed soon.

Which version of Amulet are you using and which version of the game are you using?
Can you send some screenshots of the console errors.

**Comment by LuisBionic16** [comment] 2022-05-14 15:32
> > > We don't support experimental features. 1.18.30 should be supported in Amulet 0.9.1. If this is still an issue in Amulet 0.9.1 can someone add some more details on what the issue actually is. Do the chunks look black, red or blue? Are there errors in the console?
> > 
> > 
> > I am having this issue and it's a release version
> > > I just confirmed this is a result of the recent 1.18.30 patch on bedrock. When I open a world file that is v1.18.12, no missing chunks, but when I update it to 1.18.30, there are various broken and missing chunks.
> > 
> > 
> > Same, I am also experiencing this. I hope this gets fixed soon.
> 
> Which version of Amulet are you using and which version of the game are you using? Can you send some screenshots of the console errors.

I'm using Amulet version 0.9.2. Also I am playing on Minecraft bedrock 1.18.31. I only have screenshots of missing chunks if you want to see them. 
![Amulet V0 9 2 5_14_2022 10_30_08 AM](https://user-images.githubusercontent.com/105527819/168437447-47f4b3c9-328a-4a3e-83c0-de3ce3bc3f31.png)

**Comment by LuisBionic16** [comment] 2022-05-14 15:38
> > > > We don't support experimental features. 1.18.30 should be supported in Amulet 0.9.1. If this is still an issue in Amulet 0.9.1 can someone add some more details on what the issue actually is. Do the chunks look black, red or blue? Are there errors in the console?
> > > 
> > > 
> > > I am having this issue and it's a release version
> > > > I just confirmed this is a result of the recent 1.18.30 patch on bedrock. When I open a world file that is v1.18.12, no missing chunks, but when I update it to 1.18.30, there are various broken and missing chunks.
> > > 
> > > 
> > > Same, I am also experiencing this. I hope this gets fixed soon.
> > 
> > 
> > Which version of Amulet are you using and which version of the game are you using? Can you send some screenshots of the console errors.
> 
> I'm using Amulet version 0.9.2. Also I am playing on Minecraft bedrock 1.18.31. I only have screenshots of missing chunks if you want to see them. ![Amulet V0 9 2 5_14_2022 10_30_08 AM](https://user-images.githubusercontent.com/105527819/168437447-47f4b3c9-328a-4a3e-83c0-de3ce3bc3f31.png)

Here is a better image to show the missing chunks:
![Amulet V0 9 2 5_14_2022 10_36_33 AM](https://user-images.githubusercontent.com/105527819/168438441-89290df4-db09-44e7-80d7-ed222736fcf3.png)

**Comment by gentlegiantJGC** [comment] 2022-05-14 15:41
That is different to the previous issues. Those are just chunks that the game has not generated.
You will need to go into game and fly around (and perhaps place blocks) to force the game to save them.
Bedrock only saves chunks that has changed.

**Comment by gentlegiantJGC** [comment] 2022-05-14 15:43
I am going to close this because I believe the original issue has been fixed.

**Closed by gentlegiantJGC** 2022-05-14 15:43 UTC
Labels: type: bug, state: more information needed, priority: high

**Comment by zakman9797** [comment] 2022-08-17 22:19
This issue is still not fixed... Chunks are basically not appearing. idk if this is the same issue exactly... but when loading a minecraft bedrock world windows 10... into amulet... and then going into the world... the chunks are missing... like giant holes.
![image](https://user-images.githubusercontent.com/17104224/185253482-0ea7a239-8e18-4af8-80a6-31e732eb156a.png)
the chunks are generated in game... the amulet editor is just plain missing them when loading... not experimental... normal release. latest version of bedrock. latest version of amulet. V0.9.6. I Reopened it for the sake of I need help... if i export the selection... its not going to export the chunk... since it doesn't exist in the amulet editor.

**Comment by zakman9797** [comment] 2022-08-17 22:20
![image](https://user-images.githubusercontent.com/17104224/185253699-150a2722-5433-4f7d-ad63-07327ab6f5b2.png)

**Comment by zakman9797** [comment] 2022-08-17 22:22
![image](https://user-images.githubusercontent.com/17104224/185253913-14208f6c-f8ff-4e08-a996-6dedd4268168.png)

**Comment by zakman9797** [comment] 2022-08-17 22:22
as u can see the editor is deleting the chunk when it loads the world... but the chunk is there in the spot in the actual save.

**Comment by zakman9797** [comment] 2022-08-17 22:25
![image](https://user-images.githubusercontent.com/17104224/185254186-d5b98900-0f05-42a4-95b5-ee6295fecc4a.png)
 placing a block in the chunk... and then saving... loading the world on amulet... and now even more chunks are missing around the zone... idk what is happening. im sry for opening up a old comment wall... but this is still not fixed.

**Comment by LuisBionic16** [comment] 2022-08-17 22:28
> ![image](https://user-images.githubusercontent.com/17104224/185254186-d5b98900-0f05-42a4-95b5-ee6295fecc4a.png)
> placing a block in the chunk... and then saving... loading the world on amulet... and now even more chunks are missing around the zone... idk what is happening. im sry for opening up a old comment wall... but this is still not fixed.

That’s the same issue I have. Like I can’t really do any world editing because of this.

**Comment by zakman9797** [comment] 2022-08-17 22:43
:| i love how FAQ is like place a block and save it... :| why is this not fixed... in the code. :|

**Comment by gentlegiantJGC** [comment] 2022-08-18 07:43
To repeat what I have now said many times:
Just because a chunk is displayed in game does not mean that the game has saved the chunk.
Amulet can only display chunks the game has saved. We do not have the capacity to generate chunks.

If you have an issue that cannot be explained by this please open a new issue.
Examples:
- a chunk that was previously seen in Amulet but is now not visible
- a chunk with user placed blocks is not visible
