### ISSUE TITLE
Chunks Relight function.

### ISSUE THREAD

**Issue by Syprima** [Amulet-Team/Amulet-Map-Editor#420] opened 2021-09-17 11:32 UTC
Hello. On version 1.12.2, after inserting the structure in the game, the lighting does not work correctly.
MCEdit has a 'Relight chunk' function that fixes the problem.
I am currently exporting the structures to Amulet, but I am importing and recalculating the light in MCEdit 0.1.8 version.

Amulet is more convenient and like it much more, great job, but please solve the problem with lighting!!

So far, everyone who has encountered a similar problem on 1.12.2. Use MCEdit 0.1.8 build 665 to recalculate the light.

Examples are below.
**Importing a structure in the Amulet editor:**
![Image](https://s9.gifyu.com/images/2021-09-17_13.25.37.jpg)

**Importing a structure in the MCEdit editor + relight chunk:**
![Image2](https://s9.gifyu.com/images/2021-09-17_13.58.13.jpg)

**Comment by YiYo97** [comment] 2021-09-19 15:15
I personally use this spigot plugin as a workaround. 
https://www.spigotmc.org/resources/light-cleaner.42469/

**Comment by gentlegiantJGC** [comment] 2021-09-23 09:36
I am going to close this as a duplicate of #44 
We will at some point sort this issue

**Closed by gentlegiantJGC** 2021-09-23 09:36 UTC
