### ISSUE TITLE
X Window System error & crash

### ISSUE THREAD

**Issue by Moilleadoir** [Amulet-Team/Amulet-Map-Editor#446] opened 2021-10-27 06:21 UTC
**Description**
Using Amulet to convert a Bedrock world to Java, the conversion finishes but the program immediately disappears.

**Output**
Run from a terminal I get this output.  The conversion completes, but the world is not properly converted, though I think this is a completely different issue.
```
2021-10-27 16:57:14,996 - amulet_map_editor - INFO - Finished converting world […] to […]

(__main__.py:109056): Gdk-WARNING **: 16:57:15.005: The program '__main__.py' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadImplementation (server does not implement operation)'.
  (Details: serial 425433 error_code 17 request_code 20 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Desktop:**
 - Manjaro Linux
 - Cinnamon desktop

**Comment by gentlegiantJGC** [comment] 2021-12-12 12:26
Could you try running the program again with faulthandler enabled which should give you a better error log.
Add -X faulthandler to the command line when running the program.
https://docs.python.org/3/library/faulthandler.html

**Comment by gentlegiantJGC** [comment] 2022-05-14 09:03
Is this still an issue. If so can you provide some more details

**Comment by Moilleadoir** [comment] 2022-05-17 06:09
Don’t have a working install ATM (guessing something to do with different Python version or dependencies) or a pressing need to convert anything, but I might get some time later in the week to look at it.

**Comment by Moilleadoir** [comment] 2022-06-06 04:11
OK, I’ve reinstalled Amulet in a fresh virtualenv using pew.  It runs, but I can’t figure out how to even export now as the menus do not respond and the rest of the interface is made up of those buttons that only occasionally flash into existence on Linux.

I’ve tried this with and without export `GDK_SYNCHRONIZE=1`.

**Comment by gentlegiantJGC** [comment] 2022-06-06 08:20
Ok. I will close this issue since you can't reproduce it.
The flickering issue is #127

**Closed by gentlegiantJGC** 2022-06-06 08:20 UTC
Labels: type: bug, state: more information needed, priority: medium

**Comment by Moilleadoir** [comment] 2022-06-06 08:23
Off topic, but is there any way to do a conversion on Linux now?
