### ISSUE TITLE
world conversion bug

### ISSUE THREAD

**Issue by HowTempGeneral** [Amulet-Team/Amulet-Map-Editor#577] opened 2022-02-26 17:29 UTC
@gentlegiantJGC I have now opened the issue.
Issue:
The conversion from a Bedrock 1.17.30.4.0 world to a Bedrock 1.12.0.28.1 world causes a Windows error in the console and stops the conversion every time with Amulet 0.8.18. With Amulet 0.9.0a1 and Amulet 0.9.0a2 the program crashes at some point.
![image](https://user-images.githubusercontent.com/100471268/155852966-581670ae-2233-4047-946e-a1a5e70310be.png)

**Comment by gentlegiantJGC** [comment] 2022-04-26 10:33
Are there errors in the console? There isn't enough information here for me to debug what the issue is.

**Comment by HowTempGeneral** [comment] 2022-05-01 13:25
@gentlegiantJGC I discussed this error in Discord and you told me to post it here. Then I sent the link to this post to you in the Discord server. This is the error: https://discord.com/channels/324647192583340043/498974201416253443/940963474308223008

**Comment by gentlegiantJGC** [comment] 2022-05-11 09:54
Does this issue happen in Amulet 0.9.3b0?
I made some changes that might fix this issue.

**Comment by gentlegiantJGC** [comment] 2022-05-11 10:04
It also looks like this is a duplicate of issue #563 
Please can you document your findings there.

**Closed by gentlegiantJGC** 2022-05-11 10:04 UTC
Labels: state: more information needed, priority: medium, type: crash
