### ISSUE TITLE
[Bug Report] No blocks in 1.20.2, World not editable

### ISSUE THREAD

**Issue by Scroogeee** [Amulet-Team/Amulet-Map-Editor#978] opened 2023-09-25 10:46 UTC
### Current Behaviour:
After creating a new world in Minecraft 1.20.2 only a red checkerboard is visible. It is not possible to edit anything.

### Expected behavior:

Seeing the blocks of the world.

### Steps To Reproduce:

Create a new world in 1.20.2
Exit said world.
Open said world in Amulet.
Look around.

### Environment:

- OS: OSX
- Minecraft Platform: Java
- Minecraft Version:  1.20.2
- Amulet Version:  0.10.20

### Additional context

Could be related to #977

### Screenshots

<img width="1485" alt="Bildschirmfoto 2023-09-25 um 11 39 07" src="https://github.com/Amulet-Team/Amulet-Map-Editor/assets/30441849/1ed4514c-134a-4919-87e4-c1909a8414ae">

### Worlds

Any 1.20.2 world

**Comment by gentlegiantJGC** [comment] 2023-09-26 07:56
Duplicate of #977
please share your console logs there

**Closed as completed by gentlegiantJGC** 2023-09-26 07:56 UTC
Labels: type: bug, state: triage
