### ISSUE TITLE
[Bug Report] Water render issue

### ISSUE THREAD

**Issue by DublikuntMux** [Amulet-Team/Amulet-Map-Editor#817] opened 2022-10-29 12:33 UTC
### Current Behaviour:
If there are trapdoor on the water, then there is a layering of textures on top of each other.

### Environment:

- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.18.40
- Amulet Version: 0.10.3

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/73074789/198831685-ed0c09e1-ca25-406a-9752-4f30e5b6b35f.png)

**Comment by gentlegiantJGC** [comment] 2022-10-31 08:54
So you have a wooden trapdoor that is waterlogged?
Is the issue that they are z-fighting?

**Comment by DublikuntMux** [comment] 2022-10-31 17:48
Yes and i find new render issue with another blok.

![Screenshot](https://user-images.githubusercontent.com/73074789/199074890-dccbdb2e-c6bc-42fc-850c-7944bf119448.png)

**Comment by gentlegiantJGC** [comment] 2022-11-01 10:24
I am going to say the z-fighting geometry is working as intended. All water blocks are displayed as a solid block because the models are very complex.
The tinting issue is a duplicate of #527

**Closed as completed by gentlegiantJGC** 2022-11-01 10:24 UTC
Labels: type: bug, state: triage
