### ISSUE TITLE
[Bug Report] Bedrock to Java is not loaded properly in the client

### ISSUE THREAD

**Issue by Flonja** [Amulet-Team/Amulet-Map-Editor#666] opened 2022-05-10 08:58 UTC
### Current Behaviour:
When copying a part of a Bedrock map (1.18.30) into Java Edition (1.12.2) it saves successfully, but when opening the world on a vanilla client it reverts back the "Amulet" chunks:
```
[10:37:09] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[10:37:09] [Server thread/INFO]: Generating keypair
[10:37:09] [Server thread/INFO]: Loaded 488 advancements
[10:37:09] [Server thread/INFO]: Preparing start region for level 0
[10:37:09] [Server thread/WARN]: Could not set level chunk heightmap, array length is 0 instead of 256
[10:37:09] [Server thread/ERROR]: Couldn't load chunk
java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at axs.<init>(SourceFile:16) ~[1.12.2.jar:?]
	at aye.a(SourceFile:315) ~[1.12.2.jar:?]
	at aye.a(SourceFile:97) ~[1.12.2.jar:?]
	at aye.a(SourceFile:72) ~[1.12.2.jar:?]
	at on.f(SourceFile:124) [1.12.2.jar:?]
	at on.b(SourceFile:81) [1.12.2.jar:?]
	at on.c(SourceFile:95) [1.12.2.jar:?]
	at net.minecraft.server.MinecraftServer.l(SourceFile:328) [1.12.2.jar:?]
	at chd.a(SourceFile:114) [1.12.2.jar:?]
	at chd.j(SourceFile:130) [1.12.2.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:434) [1.12.2.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

### Expected behavior:
Seeing my copied structures from Bedrock (1.18.30) in my Java (1.12.2) world.

### Steps To Reproduce:
1. Have a (small) structure to copy.
2. Paste it into a Java (1.12.2) world. *Note: that this world was created with the void superflat preset*
3. :tada:

### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java
- Minecraft Version: 1.12.2
- Amulet Version: V0.9.2

**Comment by Flonja** [comment] 2022-05-10 09:09
Alright, should I close this issue now or keep it open until it's a stable release?

**Comment by gentlegiantJGC** [comment] 2022-05-10 09:14
I will close it since it is fixed. If you can reproduce the issue in the beta let me know.

**Closed by gentlegiantJGC** 2022-05-10 09:14 UTC
Labels: type: bug, state: triage
