### ISSUE TITLE
[Bug Report] failed chunk builder compiling in archlinux

### ISSUE THREAD

**Issue by skeyvin** [Amulet-Team/Amulet-Map-Editor#800] opened 2022-09-27 11:46 UTC
### Current Behaviour:
i try to compile it on archlinux with `sudo python3.9 setup.py install`
after resolving the issues with deprecated numpy 
if i use pip install it failed at deprecated numpy 
i get
 ```
/usr/bin/ld: cannot find build/temp.linux-x86_64-3.9/amulet_map_editor/api/opengl/mesh/level/chunk/chunk_builder_cy.o: No such file or directory
```
i have tried this inside and outside a virtual env with the same result

**Comment by gentlegiantJGC** [comment] 2022-09-27 12:45
Duplicate of #769

**Closed as completed by gentlegiantJGC** 2022-09-27 12:45 UTC
Labels: type: bug, state: triage
