### ISSUE TITLE
[Bug Report] Application hangs after downloading

### ISSUE THREAD

**Issue by duch3201** [Amulet-Team/Amulet-Map-Editor#919] opened 2023-06-14 19:05 UTC
## Bug Report

So, after I installed the pre-compiled executable from GitHub, I extracted it to a folder and launched it. However, upon launching, it only opens an empty terminal window and hangs indefinitely. The Task Manager indicates that it uses 0% CPU and approximately 11MB of RAM (note: the RAM usage slowly increases over time). There are no error messages or any other visible indications—just a blinking cursor in the terminal.

### Current Behaviour:
App does not launch, just hangs on an empty terminal window

### Expected behavior:
App should actually start and work

### Steps To Reproduce:

1. download the latest (0.10.11) binary
2. extract it to a folder
3. start it
4. a terminal blank window opens

### Environment:

- OS: Windows 
- Minecraft Platform: Java
- Minecraft Version: 1.18.1
- Amulet Version: 0.10.11

### Additional context
none

### Screenshots

![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/56601374/a511130c-3436-4eea-937c-136b7090d3db)
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/56601374/a3a8a48c-bdfb-4078-966e-ee2219ce6151)

**Comment by gentlegiantJGC** [comment] 2023-06-15 08:16
Is this a duplicate of #332 ?

**Comment by gentlegiantJGC** [comment] 2023-09-27 15:40
Is this still an issue in the newest version? I fixed an issue that had this symptom.

**Closed as completed** 2024-05-01 08:55 UTC
Labels: type: bug, state: more information needed
