### ISSUE TITLE
Sometimes, only the spawn loads

### ISSUE THREAD

**Issue by aboothered** [Amulet-Team/Amulet-Map-Editor#322] opened 2021-06-12 04:28 UTC
**Describe the bug**
After opening and closing worlds some times this bug happens. It basically loads only the closest chunks to the spawn, and that's it. To make it work properly again I have to restart Amulet. 
(I don't know if there is any connection but another issue is that very often the coords on the top of the screen stop updating and to find out where I am it is needed opening the window of coordinate)

**To Reproduce**
Pretty much random, or at least I still didn't notice the trigger behind this occurrences.

**Expected behavior**
The world loading around me as I move.

**Screenshots**
Didn't thought about capturing the problem while it was happening.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10.0.19041 Build 19041

**Comment by gentlegiantJGC** [comment] 2021-11-24 10:06
This is difficult to debug because it only happens some times.
I haven't heard reports of others having this issue.
Does it start working again if you leave it for a bit?

**Comment by gentlegiantJGC** [comment] 2021-12-09 17:20
I didn't fully understand the issue from your description but it has been reproduced in #485 
I am going to close this issue and track this issue in the new report.

**Closed by gentlegiantJGC** 2021-12-09 17:20 UTC
Labels: bug, more information needed
