### ISSUE TITLE
[Bug Report] Weird Building Bug

### ISSUE THREAD

**Issue by ghost** [Amulet-Team/Amulet-Map-Editor#889] opened 2023-04-13 15:12 UTC
I discovered a very strange bug after moving 2 of my buildings with Amulet. After removing the marked buildings (see image), the old locations throwing shadows like they are still there. If you're using shaders like Seus Renewed, you'll notice that puddles don't form in those places. For this they appear in the shifted buildings. So I don't know what went wrong or how to fix it manually in the world but I do know one thing for sure: it's very annoying.

![Location Bugs](https://user-images.githubusercontent.com/128939478/231808473-767b3ff9-19dd-4be1-b101-ca8ab6005719.jpg)

I don't know if this is essential but I am using Amulet on my 1.16.5 world.

**Comment by gentlegiantJGC** [comment] 2023-04-13 15:31
Duplicate of #44

**Closed as completed by gentlegiantJGC** 2023-04-13 15:31 UTC
Labels: type: bug, state: triage
