### ISSUE TITLE
Items in chets

### ISSUE THREAD

**Issue by NSC070** [Amulet-Team/Amulet-Map-Editor#710] opened 2022-06-11 22:28 UTC
When converting to Java I've noticed that the containers with items in them are empty.
It would be great if the conversion of items to other platforms would work or else, there is really no point in converting. Might as well just start from scratch.

**Comment by gentlegiantJGC** [comment] 2022-06-12 08:02
Duplicate of #155

**Closed by gentlegiantJGC** 2022-06-12 08:02 UTC
Labels: type: enhancement, state: triage
