### ISSUE TITLE
rain falls through pasted blocks

### ISSUE THREAD

**Issue by thedutchlord** [Amulet-Team/Amulet-Map-Editor#176] opened 2021-02-14 21:19 UTC
when you paste/import a structure and then open the world in minecraft, rain falls through all of the chanced blocks

To Reproduce:

1. copy/export a structure (somthing with a roof)
2. past/inport it
3. open the world and the rain falls through 

somehow it does not rain underground, only above ground

![2021-02-14_22 10 06](https://user-images.githubusercontent.com/79061591/107889281-c844a080-6f11-11eb-8857-e99484d8df8b.png)
(rain falling indoor)

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Version 0.7.2.8x64

**Comment by gentlegiantJGC** [comment] 2021-02-14 21:27
Duplicate of #60

**Closed by gentlegiantJGC** 2021-02-14 21:27 UTC
