### ISSUE TITLE
Flowers and Saplings in the pot aren't copied

### ISSUE THREAD

**Issue by Sodvic** [Amulet-Team/Amulet-Map-Editor#1071] opened 2024-07-01 16:23 UTC
## Bug Report
Flowers and Saplings in the pot aren't copied (I only tried with Minecraft bedrock 1.21, I don't know if this bug is also present for Java).

### Current Behaviour:
the pasted area does not keep the flowers and saplings inside the pots.

### Expected behavior:
the pasted area should keep the flowers and saplings inside the pots.

### Steps To Reproduce:
1 Create a bedrock edition world and place pots with flowers and saplings in the world
2 Go to "Amulet"
3 Click on "Open world"
4 Chose the world
5 Select the area to copy
6 Paste the area where you want
7 save
8 open the world with minecraft 1.21 and see the bug

### Environment:
- OS: Windows 10
- Minecraft Platform: Bedrock
- Minecraft Version: 1.21.1
- Amulet Version: 0.10.33

**Comment by gentlegiantJGC** [comment] 2024-08-23 13:04
We don't currently support items.
Duplicate of #155

**Closed as completed by gentlegiantJGC** 2024-08-23 13:04 UTC
Labels: type: bug, state: triage

**Comment by jtmoree-github-com** [comment] 2026-02-21 17:36
This doesn't look like the same bug as #155 which is for converting between java and bedrock.  I am only working in bedrock and the OP seems to be the same.   These items are deleted from my map when moving between amulet and bedrock.

**Comment by gentlegiantJGC** [comment] 2026-02-23 08:23
Can you open a new issue explaining your issue
