### ISSUE TITLE
My amulet screen turns blue

### ISSUE THREAD

**Issue by Harsh555555** [Amulet-Team/Amulet-Map-Editor#792] opened 2022-09-14 14:49 UTC
### Environment:

- OS: Windows | OSX | linux
- Minecraft Platform: Java | Bedrock | Education Edition
- Minecraft Version: 
- Amulet Version:

**Comment by gentlegiantJGC** [comment] 2022-10-02 08:54
I am going to close this because you have not added any information.
I assume it is a duplicate of #793

**Closed as completed by gentlegiantJGC** 2022-10-02 08:54 UTC
Labels: type: bug, state: more information needed, state: triage
