### ISSUE TITLE
[Bug Report] Lighting problems after importing schematics

### ISSUE THREAD

**Issue by Rabbit0w0** [Amulet-Team/Amulet-Map-Editor#1008] opened 2023-12-18 16:00 UTC
## Bug Report
The lighting of the map glitches after importing schematics
### Current Behaviour:
Glitching lighting
### Expected behavior:
Normal lighting
### Environment:

- OS: Windows
- Minecraft Platform: Java
- Minecraft Version: 1.20.1
- Amulet Version: 0.10.27

**Comment by wildwitchwest** [comment] 2023-12-21 11:57
this happens to me with bedrock as well. i've looked all over the internet and it's a common problem across minecraft when they changed their lighting system

**Comment by gentlegiantJGC** [comment] 2024-01-07 15:24
Duplicate of #44

**Closed as completed by gentlegiantJGC** 2024-01-07 15:24 UTC
Labels: type: bug, state: triage
