### ISSUE TITLE
[Bug Report] UI scaling issue causes some controls to be invisible

### ISSUE THREAD

**Issue by yqs112358** [Amulet-Team/Amulet-Map-Editor#716] opened 2022-06-22 06:57 UTC
## Bug Report
UI scaling issue causes some controls to be invisible. And the size of controls & boxes cannot be changed so there is no way to fix it by myself

### Current Behaviour:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/37969157/174962866-b60ef218-ddd3-4b0e-b5a7-dd3c87408a7a.png">
There should be a confirm button at the bottom but I have no way to access it

### Expected behavior:
The size of boxes and position of borders can be dragged by the mouse to change it size, or the list itself can be scrolled to see all content inside.

### Steps To Reproduce:
Change your desktop scale to 150% or bigger to reproduct (because on laptops these scale level is common)

### Environment:
- OS: Windows
- Minecraft Platform: Bedrock
- Minecraft Version: 1.19
- Amulet Version: 0.9.6

### Screenshots
Above in the problem report

**Comment by gentlegiantJGC** [comment] 2022-06-26 13:50
Duplicate of #450 
This is fixed in the next version

**Closed by gentlegiantJGC** 2022-06-26 13:50 UTC
Labels: type: bug, state: triage

**Comment by yqs112358** [comment] 2022-06-26 14:13
Thanks a lot 🤗
