### ISSUE TITLE
[Bug Report] Fail To Build With Python 3.10.0

### ISSUE THREAD

**Issue by MCBEModder2020** [Amulet-Team/Amulet-Map-Editor#797] opened 2022-09-21 13:31 UTC
``

### Current Behaviour:

Fails To Build On M1 Mac With Python 3.10

### Expected behavior:

Builds Sucessfully

### Steps To Reproduce:

look at log for all of what i did
1. make a venv
2. install the build and run deps
3. build

### Environment:

- OS: MacOS For M1
- Amulet Version: Commit 4d8fea74a066b985fd3461e20a75efd68705d3e1

### Additional context

[log.log](https://gist.github.com/TheKidThatCodes/e8cff28bc2d4ca2391beaffaebd45705)

**Comment by gentlegiantJGC** [comment] 2022-09-21 13:54
This is a duplicate of #769

**Closed as completed by gentlegiantJGC** 2022-09-21 13:54 UTC
Labels: type: bug, state: triage
