### ISSUE TITLE
[Bug Report] Delete area will cause incorrect shadows

### ISSUE THREAD

**Issue by Jackstar1212** [Amulet-Team/Amulet-Map-Editor#863] opened 2023-01-07 11:46 UTC
## Bug Report

When using the map editor, after selecting an area to delete a square, open the game to load the world will find problems with shadows, there are many large areas of black shadows. Preliminary investigation of the problem may be in the deletion of the square is actually filled with air cubes here, the software filled air cubes were incorrectly identified by the game as a blocking light cubes. If the location of these air cubes filled with cubes repositioned cubes and then broken, the light shadows can be restored to normal.

### Expected:
Shadow should be correctly loaded. 

### Steps To Reproduce:
1. Open a minecraft world.
2. Select a large area.
3. Delete this area and save the world.
5. Start game and load this world.
6. You will see strange shadow in the modified area.
### Environment:

- OS: Windows 11
- Minecraft Platform: Java 
- Minecraft Version: 1.12.2、1.19.3
- Amulet Version: 0.10.7
![Image](https://user-images.githubusercontent.com/42300522/211149015-dc2f490a-dde8-4423-85d6-e4bb14f6390a.jpg)

**Comment by gentlegiantJGC** [comment] 2023-01-14 09:24
Duplicate of #44

**Closed as completed by gentlegiantJGC** 2023-01-14 09:24 UTC
Labels: type: bug, state: triage
