### ISSUE TITLE
[Feature Request] Abillity to import .litematic files

### ISSUE THREAD

**Issue by NotToxicDev** [Amulet-Team/Amulet-Map-Editor#631] opened 2022-04-07 13:45 UTC
### The Problem

I have a schematic i'd like to import into a world that is made using the Litematica mod. This doesn't work.

### Feature Description

I'd like there to be a feature where you can import .litematic files into a world in amulet.

### Alternatives

- Convert the .litematic file into a construction file. (this is not possible)
- Build the litematic in your world instead of using amulet (this is annoying af)

### Additional context

I have a town that needs planning so im copying the terrain from a server to a singleplayer world using schematics.

**Comment by gentlegiantJGC** [comment] 2022-04-09 10:04
Duplicate of #520

**Closed by gentlegiantJGC** 2022-04-09 10:04 UTC
Labels: enhancement
