### ISSUE TITLE
[Bug Report]When the save from Bedrock 1.18 is converted to a Java, fences are not automatically connected

### ISSUE THREAD

**Issue by RSCENTCOM** [Amulet-Team/Amulet-Map-Editor#999] opened 2023-11-07 09:03 UTC
**Bug Report**
When the save from Bedrock 1.18 is converted to a Java, fences are not automatically connected

**Current Behaviour:**
When the save from Bedrock 1.18 is converted to a Java, fences are not automatically connected，This error does not occur in 1.18 and below, and is also displayed in the 3D editor

**Expected behavior:**
When the Bedrock  save is converted to  Java, fences should be connected together.Hope you can fix it soon, thank you very much.

 **Environment:**
 OS: Windows
-Minecraft Platform: Bedrock
-Minecraft Version: 1.20.32
-Amulet Version: 0.10.25

**Screenshots**
![SH2023-11-07 165138](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/103917088/db50b748-1f8d-4345-81f4-f636f29c5671)

**Comment by gentlegiantJGC** [comment] 2023-11-07 09:53
Duplicate of #726

**Closed as completed by gentlegiantJGC** 2023-11-07 09:53 UTC
Labels: type: bug, state: triage
