### ISSUE TITLE
[Feature Request] edit .schematics directly

### ISSUE THREAD

**Issue by ImEthanBradberry** [Amulet-Team/Amulet-Map-Editor#709] opened 2022-06-11 19:35 UTC
As of right now you would need to import a .schematic file into a world, then edit it. In some occasions you would want to not get out of the .schematic format. For instance, it is common to use .schematic files as scenarios in MineImator. With MCedit one was able to edit directly on .schematic, and quickly export and import within MineImator. With Amulet one has to do this intermediate step of getting the .schematic file in and out of an empty world save which is insanely time consuming since you have to select what constitutes the .schematic scenario, export, import it in MineImator, everytime you want to make a quick change. Could you possibly have this by next update?

Thanks

**Comment by gentlegiantJGC** [comment] 2022-06-12 08:02
Duplicate of #274

**Closed by gentlegiantJGC** 2022-06-12 08:02 UTC
Labels: type: enhancement, state: triage
