### ISSUE TITLE
Add option to remember last coordinate position when reopening a world.

### ISSUE THREAD

**Issue by nl255** [Amulet-Team/Amulet-Map-Editor#275] opened 2021-04-24 01:14 UTC
Currently Amulet always starts at coordinates 0,0 regardless of what you were doing last time.  It would be nice to have an option to make Amulet remember whatever coordinates you were last at in that world when you last closed it in Amulet.

**Comment by SolarPH** [comment] 2021-04-24 06:08
I think an ability of the 3D editor to read current player data coordinate values (from local and multiplayer accounts) is the best option, since any map can be opened on Amulet, and having Amulet to start on the last 3D editor coordinates can make you easily lose sight of a generated terrain, specially if the last coordinates opened is too far.

**Comment by gentlegiantJGC** [comment] 2021-04-24 09:36
I plan to add a system that is able to expose some player data so that this is possible.
This is however a duplicate of #87

**Closed by gentlegiantJGC** 2021-04-24 09:36 UTC
