### ISSUE TITLE
[Bug Report] No Loot In Naturally Generated Chest

### ISSUE THREAD

**Issue by Bicybicc** [Amulet-Team/Amulet-Map-Editor#1115] opened 2024-11-14 07:43 UTC
## Bug Report
When converting java worlds over to bedrock, naturally generated chest loot doesn't convert over (world size is 5000k)
chest are empty in every structure.   

I do not know if the issue is the same converting bedrock worlds to java.

**Comment by gentlegiantJGC** [comment] 2024-11-14 08:06
Duplicate of #155

**Closed as completed by gentlegiantJGC** 2024-11-14 08:06 UTC
Labels: type: bug, state: triage
