### ISSUE TITLE
All Blocks rotated, when rotating a selection

### ISSUE THREAD

**Issue by erstervonelf** [Amulet-Team/Amulet-Map-Editor#163] opened 2021-01-28 07:55 UTC
**Describe the bug**
When you copy something and when you also rotate it, it rotates all the blocks in the selection, then your builds are destroyed, because it rotates all blocks in selection. 

**To Reproduce**
1. Go to 'Select' and select something you want
2. Click on 'Copy'
3. Click on 'Paste'
4. Click on 'ry' or on 'rx' or on 'rz' and enter a number
5. See error :All Blocks in selection are now rotated

**Expected behavior**
When you enter a number in 'ry' or 'rz' or 'rx', when you paste it, it will rotate all blocks in your selection.

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/78137780/106106180-6fb98900-6145-11eb-9eec-e5f04ae61723.PNG)
I´m selecting something

![screenshot_2](https://user-images.githubusercontent.com/78137780/106106301-a099be00-6145-11eb-99d0-7d6b4efaf532.png)
I´m in the paste menu

![screenshot_3](https://user-images.githubusercontent.com/78137780/106106417-c9ba4e80-6145-11eb-9deb-84730b169376.png)
I´m rotating in 'ry'

![screenshot_4](https://user-images.githubusercontent.com/78137780/106106521-f53d3900-6145-11eb-85cd-8b88b6f460ee.png)
I´m pasting the rotated thing, then the all the pasted blocks are rotated

**Desktop (please complete the following information):**
 - OS: Windows 10, 64-bit
 - Version 20H2
 - Amulet 0.7.2.8

**Comment by gentlegiantJGC** [comment] 2021-02-01 13:57
Duplicate of #74 
Please search before posting a new bug

**Closed by gentlegiantJGC** 2021-02-01 13:57 UTC
