### ISSUE TITLE
Can't build on MacOS Big Sur

### ISSUE THREAD

**Issue by Jason-Silla** [Amulet-Team/Amulet-Map-Editor#466] opened 2021-11-25 17:29 UTC
I can't seem to be able to build amulet on macOS Big Sur. I don't know if I'm the only one having this issue, but if you can help me figure out how to install amulet, I'd be more than grateful!

**Comment by gentlegiantJGC** [comment] 2021-11-25 17:47
Is there an error?

**Comment by Jason-Silla** [comment] 2021-11-26 01:21
Ya. I am getting the compiling error.

`f.write(err)
io.UnsupportedOperation: not writable`

**Comment by Jason-Silla** [comment] 2021-11-27 03:37
> Is there an error?

Ya. I am getting the compiling error.

`f.write(err)
io.UnsupportedOperation: not writable`

**Comment by gentlegiantJGC** [comment] 2021-11-27 07:48
Looks like a duplicate of #455

**Closed by gentlegiantJGC** 2021-11-27 07:48 UTC
