### ISSUE TITLE
It dont work on loading the 3D view

### ISSUE THREAD

**Issue by szdytom** [Amulet-Team/Amulet-Map-Editor#506] opened 2021-12-18 06:37 UTC
**Has this bug already been reported? Please check if there is a bug report already open that matches this.**

**Describe the bug**
It reports errors like these when i am first opening 3D view of a map
```
2021-12-18 14:16:43,727 - amulet_map_editor - CRITICAL - Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 84, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 130, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 229, in enable
wx._core.wxAssertionError: C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

2021-12-18 14:16:59,270 - amulet_map_editor - CRITICAL - Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 84, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 130, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 229, in enable
wx._core.wxAssertionError: C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 84, in enable
  File "amulet_map_editor\programs\edit\api\canvas\edit_canvas.py", line 130, in enable
  File "amulet_map_editor\programs\edit\api\canvas\base_edit_canvas.py", line 229, in enable
wx._core.wxAssertionError: C++ assertion "IsShown()" failed at ..\..\src\common\glcmn.cpp(84) in wxGLCanvasBase::SetCurrent(): can't make hidden GL canvas current

2021-12-18 14:17:03,551 - amulet_map_editor - CRITICAL - Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 53, in enable
RuntimeError: wrapped C/C++ object of type Gauge has been deleted

2021-12-18 14:17:09,197 - amulet_map_editor - CRITICAL - Traceback (most recent call last):
  File "amulet_map_editor\api\framework\pages\world_page.py", line 155, in _enable_active
  File "amulet_map_editor\programs\edit\edit.py", line 53, in enable
RuntimeError: wrapped C/C++ object of type Gauge has been deleted
```

**To Reproduce**
1. Load a map
2. Click on '3D' tab

**Expected behavior**
Load 3D view correctly

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version lastest(v0.8.17b0)

**Comment by Retr089** [comment] 2021-12-19 05:35
I don't know whats causing it, but it seems to happen when you open a 1.18 world. It works on 1.17.

**Comment by szdytom** [comment] 2021-12-20 00:02
it seems that Amulet dont work for any world that has ever been opened by Minecraft 1.18 before, even if it is generated by 1.17
I've tried to generate a new world with 1.17 and it then worked.

**Comment by PowerP** [comment] 2021-12-23 17:12
It also does not load the 2D on 1.18 maps.

**Comment by gentlegiantJGC** [comment] 2022-01-10 15:12
This is a duplicate of #402

**Closed by gentlegiantJGC** 2022-01-10 15:12 UTC
