### ISSUE TITLE
Schematics in Amulet Map Editor

### ISSUE THREAD

**Issue by HJBLink** [Amulet-Team/Amulet-Map-Editor#24] opened 2020-04-10 20:19 UTC
Is there a way I can use schematics in the Editor? I was trying to make a map with this program, I made a schematic to bring to my new world, but I can't use a schematic. Any solution?

**Comment by Podshot** [comment] 2020-04-10 20:21
This is a duplicate of #23, please see my comment on that issue for my explanation

**Closed** 2020-04-12 08:32 UTC
Labels: duplicate
